/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Collections.ObjectModel;
using ConsoleDemo.ApiClient;
using ConsoleDemo.Model;

namespace ConsoleDemo.ApiServices;

/// <summary>
/// Represents a collection of functions to interact with the API endpoints
/// </summary>
public interface IDictionaryApi : IApiAccessor
{
    #region Asynchronous Operations
    /// <summary>
    /// Get Dictionary with (tree of) classes
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">The URI of the dictionary. The option \&quot;latest\&quot; is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="useNestedClasses">Set to true to get classes in a nested structure.  You can&#x27;t use this option if you are using pagination. (optional)</param>
    /// <param name="classType">Optional filter on class type. Possible values are \&quot;Class\&quot;, \&quot;GroupOfProperties\&quot;, \&quot;AlternativeUse\&quot; and \&quot;Material\&quot;. (optional)</param>
    /// <param name="searchText">Optional filter text.  Ignored when UseNestedClasses &#x3D; true (optional)</param>
    /// <param name="relatedIfcEntity">Optional filter on related IFC entity. It accepts an IFC entity code (e.g. IfcWall) or uri (e.g. https://identifier.buildingsmart.org/uri/buildingsmart/ifc/4.3/class/IfcWall).  When a code is supplied, finding matching classes ignores the IFC version.  Ignored when UseNestedClasses &#x3D; true (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <param name="languageCode">Specify language (case sensitive). For those items the text is not available in the requested language, the text will be returned in the default language of the dictionary (optional)</param>
    /// <returns>Task of DictionaryClassesResponseContractV1Classes</returns>
    Task<DictionaryClassesResponseContractV1Classes> DictionaryClassesGetWithClassesAsync (string uri, bool? useNestedClasses = null, string classType = null, string searchText = null, string relatedIfcEntity = null, int? offset = null, int? limit = null, string languageCode = null);

    /// <summary>
    /// Get Dictionary with (tree of) classes
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">The URI of the dictionary. The option \&quot;latest\&quot; is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="useNestedClasses">Set to true to get classes in a nested structure.  You can&#x27;t use this option if you are using pagination. (optional)</param>
    /// <param name="classType">Optional filter on class type. Possible values are \&quot;Class\&quot;, \&quot;GroupOfProperties\&quot;, \&quot;AlternativeUse\&quot; and \&quot;Material\&quot;. (optional)</param>
    /// <param name="searchText">Optional filter text.  Ignored when UseNestedClasses &#x3D; true (optional)</param>
    /// <param name="relatedIfcEntity">Optional filter on related IFC entity. It accepts an IFC entity code (e.g. IfcWall) or uri (e.g. https://identifier.buildingsmart.org/uri/buildingsmart/ifc/4.3/class/IfcWall).  When a code is supplied, finding matching classes ignores the IFC version.  Ignored when UseNestedClasses &#x3D; true (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <param name="languageCode">Specify language (case sensitive). For those items the text is not available in the requested language, the text will be returned in the default language of the dictionary (optional)</param>
    /// <returns>Task of ApiResponse (DictionaryClassesResponseContractV1Classes)</returns>
    Task<ApiResponse<DictionaryClassesResponseContractV1Classes>> DictionaryClassesGetWithClassesAsyncWithHttpInfo (string uri, bool? useNestedClasses = null, string classType = null, string searchText = null, string relatedIfcEntity = null, int? offset = null, int? limit = null, string languageCode = null);
    /// <summary>
    /// Download a file with an export of a dictionary in format supported by Sketchup.  This API replaces /api/RequestExportFile/preview
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="dictionaryUri">The uri of the dictionary to be downloaded, including version number, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/1.1. You can replace the version number by \&quot;latest\&quot; to automatically get the latest (active) version of the dictionary</param>
    /// <returns>Task of byte[]</returns>
    Task<byte[]> DictionaryDownloadSketchupAsync (string dictionaryUri);

    /// <summary>
    /// Download a file with an export of a dictionary in format supported by Sketchup.  This API replaces /api/RequestExportFile/preview
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="dictionaryUri">The uri of the dictionary to be downloaded, including version number, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/1.1. You can replace the version number by \&quot;latest\&quot; to automatically get the latest (active) version of the dictionary</param>
    /// <returns>Task of ApiResponse (byte[])</returns>
    Task<ApiResponse<byte[]>> DictionaryDownloadSketchupAsyncWithHttpInfo (string dictionaryUri);
    /// <summary>
    /// Get list of available Dictionaries with optional filtering.
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">Optional parameter to filter by first part of URI. Use this one to get details of just one dictionary version  or, if you leave out the version number at the end, get all the versions of a dictionary.  Example: https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/ (optional)</param>
    /// <param name="includeTestDictionaries">Should test dictionaries be included in the result? By default it is set to false.  This option is ignored if you specify a URI. (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of DictionaryResponseContractV1</returns>
    Task<DictionaryResponseContractV1> DictionaryGetAsync (string uri = null, bool? includeTestDictionaries = null, int? offset = null, int? limit = null);

    /// <summary>
    /// Get list of available Dictionaries with optional filtering.
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">Optional parameter to filter by first part of URI. Use this one to get details of just one dictionary version  or, if you leave out the version number at the end, get all the versions of a dictionary.  Example: https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/ (optional)</param>
    /// <param name="includeTestDictionaries">Should test dictionaries be included in the result? By default it is set to false.  This option is ignored if you specify a URI. (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of ApiResponse (DictionaryResponseContractV1)</returns>
    Task<ApiResponse<DictionaryResponseContractV1>> DictionaryGetAsyncWithHttpInfo (string uri = null, bool? includeTestDictionaries = null, int? offset = null, int? limit = null);
    /// <summary>
    /// Get Dictionary with its properties
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">The URI of the dictionary. The option \&quot;latest\&quot; is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="searchText">Optional filter text. (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <param name="languageCode">Specify language (case sensitive). For those items the text is not available in the requested language, the text will be returned in the default language of the dictionary (optional)</param>
    /// <returns>Task of DictionaryPropertiesResponseContractV1</returns>
    Task<DictionaryPropertiesResponseContractV1> DictionaryGetWithPropertiesAsync (string uri, string searchText = null, int? offset = null, int? limit = null, string languageCode = null);

    /// <summary>
    /// Get Dictionary with its properties
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">The URI of the dictionary. The option \&quot;latest\&quot; is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="searchText">Optional filter text. (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <param name="languageCode">Specify language (case sensitive). For those items the text is not available in the requested language, the text will be returned in the default language of the dictionary (optional)</param>
    /// <returns>Task of ApiResponse (DictionaryPropertiesResponseContractV1)</returns>
    Task<ApiResponse<DictionaryPropertiesResponseContractV1>> DictionaryGetWithPropertiesAsyncWithHttpInfo (string uri, string searchText = null, int? offset = null, int? limit = null, string languageCode = null);
    #endregion Asynchronous Operations
}

/// <summary>
/// Represents a collection of functions to interact with the API endpoints
/// </summary>
public partial class DictionaryApi : IDictionaryApi
{
    private ExceptionFactory _exceptionFactory = (name, response) => null;

    /// <summary>
    /// Initializes a new instance of the <see cref="DictionaryApi"/> class.
    /// </summary>
    /// <returns></returns>
    public DictionaryApi(string basePath)
    {
        Configuration = new Configuration { BasePath = basePath };

        ExceptionFactory = Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="DictionaryApi"/> class
    /// </summary>
    /// <returns></returns>
    public DictionaryApi()
    {
        Configuration = Configuration.Default;

        ExceptionFactory = Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="DictionaryApi"/> class
    /// using Configuration object
    /// </summary>
    /// <param name="configuration">An instance of Configuration</param>
    /// <returns></returns>
    public DictionaryApi(Configuration configuration = null)
    {
        if (configuration == null) // use the default one in Configuration
            Configuration = Configuration.Default;
        else
            Configuration = configuration;

        ExceptionFactory = Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    /// Gets the base path of the API client.
    /// </summary>
    /// <value>The base path</value>
    public string GetBasePath()
    {
        return Configuration.ApiClient.RestClient.Options.BaseUrl.ToString();
    }

    /// <summary>
    /// Sets the base path of the API client.
    /// </summary>
    /// <value>The base path</value>
    [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
    public void SetBasePath(string basePath)
    {
        // do nothing
    }

    /// <summary>
    /// Gets or sets the configuration object
    /// </summary>
    /// <value>An instance of the Configuration</value>
    public Configuration Configuration {get; set;}

    /// <summary>
    /// Provides a factory method hook for the creation of exceptions.
    /// </summary>
    public ExceptionFactory ExceptionFactory
    {
        get
        {
            if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
            {
                throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
            }
            return _exceptionFactory;
        }
        set { _exceptionFactory = value; }
    }

    /// <summary>
    /// Gets the default header.
    /// </summary>
    /// <returns>Dictionary of HTTP header</returns>
    [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
    public IDictionary<string, string> DefaultHeader()
    {
        return new ReadOnlyDictionary<string, string>(Configuration.DefaultHeader);
    }

    /// <summary>
    /// Add default header.
    /// </summary>
    /// <param name="key">Header field name.</param>
    /// <param name="value">Header field value.</param>
    /// <returns></returns>
    [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
    public void AddDefaultHeader(string key, string value)
    {
        Configuration.AddDefaultHeader(key, value);
    }

    /// <summary>
    /// Get Dictionary with (tree of) classes 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">The URI of the dictionary. The option \&quot;latest\&quot; is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="useNestedClasses">Set to true to get classes in a nested structure.  You can&#x27;t use this option if you are using pagination. (optional)</param>
    /// <param name="classType">Optional filter on class type. Possible values are \&quot;Class\&quot;, \&quot;GroupOfProperties\&quot;, \&quot;AlternativeUse\&quot; and \&quot;Material\&quot;. (optional)</param>
    /// <param name="searchText">Optional filter text.  Ignored when UseNestedClasses &#x3D; true (optional)</param>
    /// <param name="relatedIfcEntity">Optional filter on related IFC entity. It accepts an IFC entity code (e.g. IfcWall) or uri (e.g. https://identifier.buildingsmart.org/uri/buildingsmart/ifc/4.3/class/IfcWall).  When a code is supplied, finding matching classes ignores the IFC version.  Ignored when UseNestedClasses &#x3D; true (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <param name="languageCode">Specify language (case sensitive). For those items the text is not available in the requested language, the text will be returned in the default language of the dictionary (optional)</param>
    /// <returns>DictionaryClassesResponseContractV1Classes</returns>
    public DictionaryClassesResponseContractV1Classes DictionaryClassesGetWithClasses (string uri, bool? useNestedClasses = null, string classType = null, string searchText = null, string relatedIfcEntity = null, int? offset = null, int? limit = null, string languageCode = null)
    {
        ApiResponse<DictionaryClassesResponseContractV1Classes> localVarResponse = DictionaryClassesGetWithClassesWithHttpInfo(uri, useNestedClasses, classType, searchText, relatedIfcEntity, offset, limit, languageCode);
        return localVarResponse.Data;
    }

    /// <summary>
    /// Get Dictionary with (tree of) classes 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">The URI of the dictionary. The option \&quot;latest\&quot; is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="useNestedClasses">Set to true to get classes in a nested structure.  You can&#x27;t use this option if you are using pagination. (optional)</param>
    /// <param name="classType">Optional filter on class type. Possible values are \&quot;Class\&quot;, \&quot;GroupOfProperties\&quot;, \&quot;AlternativeUse\&quot; and \&quot;Material\&quot;. (optional)</param>
    /// <param name="searchText">Optional filter text.  Ignored when UseNestedClasses &#x3D; true (optional)</param>
    /// <param name="relatedIfcEntity">Optional filter on related IFC entity. It accepts an IFC entity code (e.g. IfcWall) or uri (e.g. https://identifier.buildingsmart.org/uri/buildingsmart/ifc/4.3/class/IfcWall).  When a code is supplied, finding matching classes ignores the IFC version.  Ignored when UseNestedClasses &#x3D; true (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <param name="languageCode">Specify language (case sensitive). For those items the text is not available in the requested language, the text will be returned in the default language of the dictionary (optional)</param>
    /// <returns>ApiResponse of DictionaryClassesResponseContractV1Classes</returns>
    public ApiResponse< DictionaryClassesResponseContractV1Classes > DictionaryClassesGetWithClassesWithHttpInfo (string uri, bool? useNestedClasses = null, string classType = null, string searchText = null, string relatedIfcEntity = null, int? offset = null, int? limit = null, string languageCode = null)
    {
        // verify the required parameter 'uri' is set
        if (uri == null)
            throw new BsddApiException(400, "Missing required parameter 'uri' when calling DictionaryApi->DictionaryClassesGetWithClasses");

        var localVarPath = "/api/Dictionary/v1/Classes";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[] {
        };
        string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new string[] {
            "text/plain",
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "text/html",
            "text/turtle",
            "application/x-turtle",
            "application/rdf+xml"
        };
        string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (uri != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Uri", uri)); // query parameter
        if (useNestedClasses != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "UseNestedClasses", useNestedClasses)); // query parameter
        if (classType != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "ClassType", classType)); // query parameter
        if (searchText != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "SearchText", searchText)); // query parameter
        if (relatedIfcEntity != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "RelatedIfcEntity", relatedIfcEntity)); // query parameter
        if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Offset", offset)); // query parameter
        if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Limit", limit)); // query parameter
        if (languageCode != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "languageCode", languageCode)); // query parameter

        // make the HTTP request
        RestResponse localVarResponse = (RestResponse) Configuration.ApiClient.CallApi(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        int localVarStatusCode = (int) localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            Exception exception = ExceptionFactory("DictionaryClassesGetWithClasses", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<DictionaryClassesResponseContractV1Classes>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (DictionaryClassesResponseContractV1Classes) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DictionaryClassesResponseContractV1Classes)));
    }

    /// <summary>
    /// Get Dictionary with (tree of) classes 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">The URI of the dictionary. The option \&quot;latest\&quot; is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="useNestedClasses">Set to true to get classes in a nested structure.  You can&#x27;t use this option if you are using pagination. (optional)</param>
    /// <param name="classType">Optional filter on class type. Possible values are \&quot;Class\&quot;, \&quot;GroupOfProperties\&quot;, \&quot;AlternativeUse\&quot; and \&quot;Material\&quot;. (optional)</param>
    /// <param name="searchText">Optional filter text.  Ignored when UseNestedClasses &#x3D; true (optional)</param>
    /// <param name="relatedIfcEntity">Optional filter on related IFC entity. It accepts an IFC entity code (e.g. IfcWall) or uri (e.g. https://identifier.buildingsmart.org/uri/buildingsmart/ifc/4.3/class/IfcWall).  When a code is supplied, finding matching classes ignores the IFC version.  Ignored when UseNestedClasses &#x3D; true (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <param name="languageCode">Specify language (case sensitive). For those items the text is not available in the requested language, the text will be returned in the default language of the dictionary (optional)</param>
    /// <returns>Task of DictionaryClassesResponseContractV1Classes</returns>
    public async Task<DictionaryClassesResponseContractV1Classes> DictionaryClassesGetWithClassesAsync (string uri, bool? useNestedClasses = null, string classType = null, string searchText = null, string relatedIfcEntity = null, int? offset = null, int? limit = null, string languageCode = null)
    {
        ApiResponse<DictionaryClassesResponseContractV1Classes> localVarResponse = await DictionaryClassesGetWithClassesAsyncWithHttpInfo(uri, useNestedClasses, classType, searchText, relatedIfcEntity, offset, limit, languageCode);
        return localVarResponse.Data;

    }

    /// <summary>
    /// Get Dictionary with (tree of) classes 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">The URI of the dictionary. The option \&quot;latest\&quot; is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="useNestedClasses">Set to true to get classes in a nested structure.  You can&#x27;t use this option if you are using pagination. (optional)</param>
    /// <param name="classType">Optional filter on class type. Possible values are \&quot;Class\&quot;, \&quot;GroupOfProperties\&quot;, \&quot;AlternativeUse\&quot; and \&quot;Material\&quot;. (optional)</param>
    /// <param name="searchText">Optional filter text.  Ignored when UseNestedClasses &#x3D; true (optional)</param>
    /// <param name="relatedIfcEntity">Optional filter on related IFC entity. It accepts an IFC entity code (e.g. IfcWall) or uri (e.g. https://identifier.buildingsmart.org/uri/buildingsmart/ifc/4.3/class/IfcWall).  When a code is supplied, finding matching classes ignores the IFC version.  Ignored when UseNestedClasses &#x3D; true (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <param name="languageCode">Specify language (case sensitive). For those items the text is not available in the requested language, the text will be returned in the default language of the dictionary (optional)</param>
    /// <returns>Task of ApiResponse (DictionaryClassesResponseContractV1Classes)</returns>
    public async Task<ApiResponse<DictionaryClassesResponseContractV1Classes>> DictionaryClassesGetWithClassesAsyncWithHttpInfo (string uri, bool? useNestedClasses = null, string classType = null, string searchText = null, string relatedIfcEntity = null, int? offset = null, int? limit = null, string languageCode = null)
    {
        // verify the required parameter 'uri' is set
        if (uri == null)
            throw new BsddApiException(400, "Missing required parameter 'uri' when calling DictionaryApi->DictionaryClassesGetWithClasses");

        var localVarPath = "/api/Dictionary/v1/Classes";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[] {
        };
        string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new string[] {
            "text/plain",
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "text/html",
            "text/turtle",
            "application/x-turtle",
            "application/rdf+xml"
        };
        string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (uri != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Uri", uri)); // query parameter
        if (useNestedClasses != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "UseNestedClasses", useNestedClasses)); // query parameter
        if (classType != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "ClassType", classType)); // query parameter
        if (searchText != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "SearchText", searchText)); // query parameter
        if (relatedIfcEntity != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "RelatedIfcEntity", relatedIfcEntity)); // query parameter
        if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Offset", offset)); // query parameter
        if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Limit", limit)); // query parameter
        if (languageCode != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "languageCode", languageCode)); // query parameter

        // make the HTTP request
        RestResponse localVarResponse = (RestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        int localVarStatusCode = (int) localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            Exception exception = ExceptionFactory("DictionaryClassesGetWithClasses", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<DictionaryClassesResponseContractV1Classes>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (DictionaryClassesResponseContractV1Classes) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DictionaryClassesResponseContractV1Classes)));
    }

    /// <summary>
    /// Download a file with an export of a dictionary in format supported by Sketchup.  This API replaces /api/RequestExportFile/preview 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="dictionaryUri">The uri of the dictionary to be downloaded, including version number, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/1.1. You can replace the version number by \&quot;latest\&quot; to automatically get the latest (active) version of the dictionary</param>
    /// <returns>byte[]</returns>
    public byte[] DictionaryDownloadSketchup (string dictionaryUri)
    {
        ApiResponse<byte[]> localVarResponse = DictionaryDownloadSketchupWithHttpInfo(dictionaryUri);
        return localVarResponse.Data;
    }

    /// <summary>
    /// Download a file with an export of a dictionary in format supported by Sketchup.  This API replaces /api/RequestExportFile/preview 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="dictionaryUri">The uri of the dictionary to be downloaded, including version number, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/1.1. You can replace the version number by \&quot;latest\&quot; to automatically get the latest (active) version of the dictionary</param>
    /// <returns>ApiResponse of byte[]</returns>
    public ApiResponse< byte[] > DictionaryDownloadSketchupWithHttpInfo (string dictionaryUri)
    {
        // verify the required parameter 'dictionaryUri' is set
        if (dictionaryUri == null)
            throw new BsddApiException(400, "Missing required parameter 'dictionaryUri' when calling DictionaryApi->DictionaryDownloadSketchup");

        var localVarPath = "/api/DictionaryDownload/sketchup/v1";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[] {
        };
        string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new string[] {
            "text/plain",
            "application/json",
            "text/json",
            "text/html",
            "text/turtle",
            "application/x-turtle",
            "application/rdf+xml",
            "application/xml",
            "text/xml"
        };
        string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (dictionaryUri != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "DictionaryUri", dictionaryUri)); // query parameter
        // authentication (aad-jwt) required
        // oauth required
        if (!string.IsNullOrEmpty(Configuration.AccessToken))
        {
            localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
        }

        // make the HTTP request
        RestResponse localVarResponse = (RestResponse) Configuration.ApiClient.CallApi(localVarPath,
            Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        int localVarStatusCode = (int) localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            Exception exception = ExceptionFactory("DictionaryDownloadSketchup", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<byte[]>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (byte[]) Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
    }

    /// <summary>
    /// Download a file with an export of a dictionary in format supported by Sketchup.  This API replaces /api/RequestExportFile/preview 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="dictionaryUri">The uri of the dictionary to be downloaded, including version number, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/1.1. You can replace the version number by \&quot;latest\&quot; to automatically get the latest (active) version of the dictionary</param>
    /// <returns>Task of byte[]</returns>
    public async Task<byte[]> DictionaryDownloadSketchupAsync (string dictionaryUri)
    {
        ApiResponse<byte[]> localVarResponse = await DictionaryDownloadSketchupAsyncWithHttpInfo(dictionaryUri);
        return localVarResponse.Data;

    }

    /// <summary>
    /// Download a file with an export of a dictionary in format supported by Sketchup.  This API replaces /api/RequestExportFile/preview 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="dictionaryUri">The uri of the dictionary to be downloaded, including version number, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/1.1. You can replace the version number by \&quot;latest\&quot; to automatically get the latest (active) version of the dictionary</param>
    /// <returns>Task of ApiResponse (byte[])</returns>
    public async Task<ApiResponse<byte[]>> DictionaryDownloadSketchupAsyncWithHttpInfo (string dictionaryUri)
    {
        // verify the required parameter 'dictionaryUri' is set
        if (dictionaryUri == null)
            throw new BsddApiException(400, "Missing required parameter 'dictionaryUri' when calling DictionaryApi->DictionaryDownloadSketchup");

        var localVarPath = "/api/DictionaryDownload/sketchup/v1";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[] {
        };
        string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new string[] {
            "text/plain",
            "application/json",
            "text/json",
            "text/html",
            "text/turtle",
            "application/x-turtle",
            "application/rdf+xml",
            "application/xml",
            "text/xml"
        };
        string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (dictionaryUri != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "DictionaryUri", dictionaryUri)); // query parameter
        // authentication (aad-jwt) required
        // oauth required
        if (!string.IsNullOrEmpty(Configuration.AccessToken))
        {
            localVarHeaderParams["Authorization"] = "Bearer " + Configuration.AccessToken;
        }

        // make the HTTP request
        RestResponse localVarResponse = (RestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
            Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        int localVarStatusCode = (int) localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            Exception exception = ExceptionFactory("DictionaryDownloadSketchup", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<byte[]>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (byte[]) Configuration.ApiClient.Deserialize(localVarResponse, typeof(byte[])));
    }

    /// <summary>
    /// Get list of available Dictionaries with optional filtering. 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">Optional parameter to filter by first part of URI. Use this one to get details of just one dictionary version  or, if you leave out the version number at the end, get all the versions of a dictionary.  Example: https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/ (optional)</param>
    /// <param name="includeTestDictionaries">Should test dictionaries be included in the result? By default it is set to false.  This option is ignored if you specify a URI. (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>DictionaryResponseContractV1</returns>
    public DictionaryResponseContractV1 DictionaryGet (string uri = null, bool? includeTestDictionaries = null, int? offset = null, int? limit = null)
    {
        ApiResponse<DictionaryResponseContractV1> localVarResponse = DictionaryGetWithHttpInfo(uri, includeTestDictionaries, offset, limit);
        return localVarResponse.Data;
    }

    /// <summary>
    /// Get list of available Dictionaries with optional filtering. 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">Optional parameter to filter by first part of URI. Use this one to get details of just one dictionary version  or, if you leave out the version number at the end, get all the versions of a dictionary.  Example: https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/ (optional)</param>
    /// <param name="includeTestDictionaries">Should test dictionaries be included in the result? By default it is set to false.  This option is ignored if you specify a URI. (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>ApiResponse of DictionaryResponseContractV1</returns>
    public ApiResponse< DictionaryResponseContractV1 > DictionaryGetWithHttpInfo (string uri = null, bool? includeTestDictionaries = null, int? offset = null, int? limit = null)
    {

        var localVarPath = "/api/Dictionary/v1";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[] {
        };
        string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new string[] {
            "text/plain",
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "text/html",
            "text/turtle",
            "application/x-turtle",
            "application/rdf+xml"
        };
        string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (uri != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Uri", uri)); // query parameter
        if (includeTestDictionaries != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "IncludeTestDictionaries", includeTestDictionaries)); // query parameter
        if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Offset", offset)); // query parameter
        if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Limit", limit)); // query parameter

        // make the HTTP request
        RestResponse localVarResponse = (RestResponse) Configuration.ApiClient.CallApi(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        int localVarStatusCode = (int) localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            Exception exception = ExceptionFactory("DictionaryGet", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<DictionaryResponseContractV1>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (DictionaryResponseContractV1) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DictionaryResponseContractV1)));
    }

    /// <summary>
    /// Get list of available Dictionaries with optional filtering. 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">Optional parameter to filter by first part of URI. Use this one to get details of just one dictionary version  or, if you leave out the version number at the end, get all the versions of a dictionary.  Example: https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/ (optional)</param>
    /// <param name="includeTestDictionaries">Should test dictionaries be included in the result? By default it is set to false.  This option is ignored if you specify a URI. (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of DictionaryResponseContractV1</returns>
    public async Task<DictionaryResponseContractV1> DictionaryGetAsync (string uri = null, bool? includeTestDictionaries = null, int? offset = null, int? limit = null)
    {
        ApiResponse<DictionaryResponseContractV1> localVarResponse = await DictionaryGetAsyncWithHttpInfo(uri, includeTestDictionaries, offset, limit);
        return localVarResponse.Data;

    }

    /// <summary>
    /// Get list of available Dictionaries with optional filtering. 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">Optional parameter to filter by first part of URI. Use this one to get details of just one dictionary version  or, if you leave out the version number at the end, get all the versions of a dictionary.  Example: https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/ (optional)</param>
    /// <param name="includeTestDictionaries">Should test dictionaries be included in the result? By default it is set to false.  This option is ignored if you specify a URI. (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of ApiResponse (DictionaryResponseContractV1)</returns>
    public async Task<ApiResponse<DictionaryResponseContractV1>> DictionaryGetAsyncWithHttpInfo (string uri = null, bool? includeTestDictionaries = null, int? offset = null, int? limit = null)
    {

        var localVarPath = "/api/Dictionary/v1";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[] {
        };
        string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new string[] {
            "text/plain",
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "text/html",
            "text/turtle",
            "application/x-turtle",
            "application/rdf+xml"
        };
        string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (uri != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Uri", uri)); // query parameter
        if (includeTestDictionaries != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "IncludeTestDictionaries", includeTestDictionaries)); // query parameter
        if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Offset", offset)); // query parameter
        if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Limit", limit)); // query parameter

        // make the HTTP request
        RestResponse localVarResponse = (RestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        int localVarStatusCode = (int) localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            Exception exception = ExceptionFactory("DictionaryGet", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<DictionaryResponseContractV1>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (DictionaryResponseContractV1) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DictionaryResponseContractV1)));
    }

    /// <summary>
    /// Get Dictionary with its properties 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">The URI of the dictionary. The option \&quot;latest\&quot; is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="searchText">Optional filter text. (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <param name="languageCode">Specify language (case sensitive). For those items the text is not available in the requested language, the text will be returned in the default language of the dictionary (optional)</param>
    /// <returns>DictionaryPropertiesResponseContractV1</returns>
    public DictionaryPropertiesResponseContractV1 DictionaryGetWithProperties (string uri, string searchText = null, int? offset = null, int? limit = null, string languageCode = null)
    {
        ApiResponse<DictionaryPropertiesResponseContractV1> localVarResponse = DictionaryGetWithPropertiesWithHttpInfo(uri, searchText, offset, limit, languageCode);
        return localVarResponse.Data;
    }

    /// <summary>
    /// Get Dictionary with its properties 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">The URI of the dictionary. The option \&quot;latest\&quot; is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="searchText">Optional filter text. (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <param name="languageCode">Specify language (case sensitive). For those items the text is not available in the requested language, the text will be returned in the default language of the dictionary (optional)</param>
    /// <returns>ApiResponse of DictionaryPropertiesResponseContractV1</returns>
    public ApiResponse< DictionaryPropertiesResponseContractV1 > DictionaryGetWithPropertiesWithHttpInfo (string uri, string searchText = null, int? offset = null, int? limit = null, string languageCode = null)
    {
        // verify the required parameter 'uri' is set
        if (uri == null)
            throw new BsddApiException(400, "Missing required parameter 'uri' when calling DictionaryApi->DictionaryGetWithProperties");

        var localVarPath = "/api/Dictionary/v1/Properties";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[] {
        };
        string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new string[] {
            "text/plain",
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "text/html",
            "text/turtle",
            "application/x-turtle",
            "application/rdf+xml"
        };
        string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (uri != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Uri", uri)); // query parameter
        if (searchText != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "SearchText", searchText)); // query parameter
        if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Offset", offset)); // query parameter
        if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Limit", limit)); // query parameter
        if (languageCode != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "languageCode", languageCode)); // query parameter

        // make the HTTP request
        RestResponse localVarResponse = (RestResponse) Configuration.ApiClient.CallApi(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        int localVarStatusCode = (int) localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            Exception exception = ExceptionFactory("DictionaryGetWithProperties", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<DictionaryPropertiesResponseContractV1>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (DictionaryPropertiesResponseContractV1) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DictionaryPropertiesResponseContractV1)));
    }

    /// <summary>
    /// Get Dictionary with its properties 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">The URI of the dictionary. The option \&quot;latest\&quot; is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="searchText">Optional filter text. (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <param name="languageCode">Specify language (case sensitive). For those items the text is not available in the requested language, the text will be returned in the default language of the dictionary (optional)</param>
    /// <returns>Task of DictionaryPropertiesResponseContractV1</returns>
    public async Task<DictionaryPropertiesResponseContractV1> DictionaryGetWithPropertiesAsync (string uri, string searchText = null, int? offset = null, int? limit = null, string languageCode = null)
    {
        ApiResponse<DictionaryPropertiesResponseContractV1> localVarResponse = await DictionaryGetWithPropertiesAsyncWithHttpInfo(uri, searchText, offset, limit, languageCode);
        return localVarResponse.Data;

    }

    /// <summary>
    /// Get Dictionary with its properties 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="uri">The URI of the dictionary. The option \&quot;latest\&quot; is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="searchText">Optional filter text. (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <param name="languageCode">Specify language (case sensitive). For those items the text is not available in the requested language, the text will be returned in the default language of the dictionary (optional)</param>
    /// <returns>Task of ApiResponse (DictionaryPropertiesResponseContractV1)</returns>
    public async Task<ApiResponse<DictionaryPropertiesResponseContractV1>> DictionaryGetWithPropertiesAsyncWithHttpInfo (string uri, string searchText = null, int? offset = null, int? limit = null, string languageCode = null)
    {
        // verify the required parameter 'uri' is set
        if (uri == null)
            throw new BsddApiException(400, "Missing required parameter 'uri' when calling DictionaryApi->DictionaryGetWithProperties");

        var localVarPath = "/api/Dictionary/v1/Properties";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[] {
        };
        string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new string[] {
            "text/plain",
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "text/html",
            "text/turtle",
            "application/x-turtle",
            "application/rdf+xml"
        };
        string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (uri != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Uri", uri)); // query parameter
        if (searchText != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "SearchText", searchText)); // query parameter
        if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Offset", offset)); // query parameter
        if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Limit", limit)); // query parameter
        if (languageCode != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "languageCode", languageCode)); // query parameter

        // make the HTTP request
        RestResponse localVarResponse = (RestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        int localVarStatusCode = (int) localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            Exception exception = ExceptionFactory("DictionaryGetWithProperties", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<DictionaryPropertiesResponseContractV1>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (DictionaryPropertiesResponseContractV1) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DictionaryPropertiesResponseContractV1)));
    }

}