/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Collections.ObjectModel;
using ConsoleDemo.ApiClient;
using ConsoleDemo.Model;

namespace ConsoleDemo.ApiServices;

/// <summary>
/// Represents a collection of functions to interact with the API endpoints
/// </summary>
public interface ISearchApi : IApiAccessor
{
    #region Asynchronous Operations
    /// <summary>
    /// Search bSDD using free text. Get list of Classes matching the text and optional additional filters.
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 3 characters (case and accent insensitive)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on.  For a class to be found it must be part of one of the given dictionaries (optional)</param>
    /// <param name="relatedIfcEntities">List of related IFC entities to filter on.  For a class to be found it must have at least one of the given Related Ifc Entities (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of ClassSearchResponseContractV1</returns>
    Task<ClassSearchResponseContractV1> ClassSearchGetAsync (string searchText, List<string> dictionaryUris = null, List<string> relatedIfcEntities = null, int? offset = null, int? limit = null);

    /// <summary>
    /// Search bSDD using free text. Get list of Classes matching the text and optional additional filters.
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 3 characters (case and accent insensitive)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on.  For a class to be found it must be part of one of the given dictionaries (optional)</param>
    /// <param name="relatedIfcEntities">List of related IFC entities to filter on.  For a class to be found it must have at least one of the given Related Ifc Entities (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of ApiResponse (ClassSearchResponseContractV1)</returns>
    Task<ApiResponse<ClassSearchResponseContractV1>> ClassSearchGetAsyncWithHttpInfo (string searchText, List<string> dictionaryUris = null, List<string> relatedIfcEntities = null, int? offset = null, int? limit = null);
    /// <summary>
    /// Search the bSDD database, get list of Classes without details.  This version uses new naming and returns one Dictionary instead of a list with always one Dictionary.  This API replaces /api/SearchList.
    /// </summary>
    /// <remarks>
    /// The details can be requested per Class via the Class API
    /// </remarks>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="dictionaryUri">The uri of the Dictionary to filter on (required). The \&quot;latest\&quot; option is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="searchText">The text to search for (case and accent insensitive) (optional)</param>
    /// <param name="languageCode">The ISO language code to search in and to return the text in (case sensitive)  If no language code specified or the text is not available in the requested language, the text will be returned in the default language of the dictionary.  If a language code has been given, the search takes place in texts of that language, otherwise searches will be done in the default language of the dictionary.  If an invalid or not supported language code is given, a Bad Request will be returned. (optional)</param>
    /// <param name="relatedIfcEntity">The official IFC entity name to filter on (case sensitive) (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of SearchInDictionaryResponseContractV1</returns>
    Task<SearchInDictionaryResponseContractV1> SearchInDictionaryGetAsync (string dictionaryUri, string searchText = null, string languageCode = null, string relatedIfcEntity = null, int? offset = null, int? limit = null);

    /// <summary>
    /// Search the bSDD database, get list of Classes without details.  This version uses new naming and returns one Dictionary instead of a list with always one Dictionary.  This API replaces /api/SearchList.
    /// </summary>
    /// <remarks>
    /// The details can be requested per Class via the Class API
    /// </remarks>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="dictionaryUri">The uri of the Dictionary to filter on (required). The \&quot;latest\&quot; option is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="searchText">The text to search for (case and accent insensitive) (optional)</param>
    /// <param name="languageCode">The ISO language code to search in and to return the text in (case sensitive)  If no language code specified or the text is not available in the requested language, the text will be returned in the default language of the dictionary.  If a language code has been given, the search takes place in texts of that language, otherwise searches will be done in the default language of the dictionary.  If an invalid or not supported language code is given, a Bad Request will be returned. (optional)</param>
    /// <param name="relatedIfcEntity">The official IFC entity name to filter on (case sensitive) (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of ApiResponse (SearchInDictionaryResponseContractV1)</returns>
    Task<ApiResponse<SearchInDictionaryResponseContractV1>> SearchInDictionaryGetAsyncWithHttpInfo (string dictionaryUri, string searchText = null, string languageCode = null, string relatedIfcEntity = null, int? offset = null, int? limit = null);
    /// <summary>
    /// Search bSDD using free text, get list of Classes and/or Properties.  Pagination options for Classes and Properties are combined. If result contains 10 classes and 5 properties, TotalCount will be 15. Classes will be listed first. Use Offset&#x3D;10 and Limit&#x3D;5, to get the 5 properties only.
    /// </summary>
    /// <remarks>
    /// The details can be requested per Class via the Class API
    /// </remarks>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 2 characters (case and accent insensitive)</param>
    /// <param name="typeFilter">Type filter: can be \&quot;Class\&quot;, \&quot;Property\&quot;, \&quot;Material\&quot;, \&quot;GroupOfProperties\&quot; of a semicolon separated list of these. Empty means all (optional)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on (optional)</param>
    /// <param name="onlyLatestVersion"> (optional)</param>
    /// <param name="onlyVerified"> (optional)</param>
    /// <param name="includeInactive"> (optional)</param>
    /// <param name="includePreview"> (optional)</param>
    /// <param name="includeSearchDescriptions"> (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of TextSearchResponseContractV2</returns>
    Task<TextSearchResponseContractV2> TextSearchGetAsync (string searchText, string typeFilter = null, List<string> dictionaryUris = null, bool? onlyLatestVersion = null, bool? onlyVerified = null, bool? includeInactive = null, bool? includePreview = null, bool? includeSearchDescriptions = null, int? offset = null, int? limit = null);

    /// <summary>
    /// Search bSDD using free text, get list of Classes and/or Properties.  Pagination options for Classes and Properties are combined. If result contains 10 classes and 5 properties, TotalCount will be 15. Classes will be listed first. Use Offset&#x3D;10 and Limit&#x3D;5, to get the 5 properties only.
    /// </summary>
    /// <remarks>
    /// The details can be requested per Class via the Class API
    /// </remarks>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 2 characters (case and accent insensitive)</param>
    /// <param name="typeFilter">Type filter: can be \&quot;Class\&quot;, \&quot;Property\&quot;, \&quot;Material\&quot;, \&quot;GroupOfProperties\&quot; of a semicolon separated list of these. Empty means all (optional)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on (optional)</param>
    /// <param name="onlyLatestVersion"> (optional)</param>
    /// <param name="onlyVerified"> (optional)</param>
    /// <param name="includeInactive"> (optional)</param>
    /// <param name="includePreview"> (optional)</param>
    /// <param name="includeSearchDescriptions"> (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of ApiResponse (TextSearchResponseContractV2)</returns>
    Task<ApiResponse<TextSearchResponseContractV2>> TextSearchGetAsyncWithHttpInfo (string searchText, string typeFilter = null, List<string> dictionaryUris = null, bool? onlyLatestVersion = null, bool? onlyVerified = null, bool? includeInactive = null, bool? includePreview = null, bool? includeSearchDescriptions = null, int? offset = null, int? limit = null);
    /// <summary>
    /// Search bSDD using free text, get list of Classes and/or Properties.  Pagination options for Classes and Properties are combined. If result contains 10 classes and 5 properties, TotalCount will be 15. Classes will be listed first. Use Offset&#x3D;10 and Limit&#x3D;5, to get the 5 properties only.
    /// </summary>
    /// <remarks>
    /// The details can be requested per Class via the Class API
    /// </remarks>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 2 characters (case and accent insensitive)</param>
    /// <param name="typeFilter">Type filter: must be \&quot;All\&quot;, \&quot;Classes\&quot; or \&quot;Properties\&quot; (optional)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of TextSearchResponseContractV1</returns>
    Task<TextSearchResponseContractV1> TextSearchV1GetAsync (string searchText, string typeFilter = null, List<string> dictionaryUris = null, int? offset = null, int? limit = null);

    /// <summary>
    /// Search bSDD using free text, get list of Classes and/or Properties.  Pagination options for Classes and Properties are combined. If result contains 10 classes and 5 properties, TotalCount will be 15. Classes will be listed first. Use Offset&#x3D;10 and Limit&#x3D;5, to get the 5 properties only.
    /// </summary>
    /// <remarks>
    /// The details can be requested per Class via the Class API
    /// </remarks>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 2 characters (case and accent insensitive)</param>
    /// <param name="typeFilter">Type filter: must be \&quot;All\&quot;, \&quot;Classes\&quot; or \&quot;Properties\&quot; (optional)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of ApiResponse (TextSearchResponseContractV1)</returns>
    Task<ApiResponse<TextSearchResponseContractV1>> TextSearchV1GetAsyncWithHttpInfo (string searchText, string typeFilter = null, List<string> dictionaryUris = null, int? offset = null, int? limit = null);
    #endregion Asynchronous Operations
}

/// <summary>
/// Represents a collection of functions to interact with the API endpoints
/// </summary>
public partial class SearchApi : ISearchApi
{
    private ExceptionFactory _exceptionFactory = (name, response) => null;

    /// <summary>
    /// Initializes a new instance of the <see cref="SearchApi"/> class.
    /// </summary>
    /// <returns></returns>
    public SearchApi(string basePath)
    {
        Configuration = new Configuration { BasePath = basePath };

        ExceptionFactory = Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="SearchApi"/> class
    /// </summary>
    /// <returns></returns>
    public SearchApi()
    {
        Configuration = Configuration.Default;

        ExceptionFactory = Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="SearchApi"/> class
    /// using Configuration object
    /// </summary>
    /// <param name="configuration">An instance of Configuration</param>
    /// <returns></returns>
    public SearchApi(Configuration configuration = null)
    {
        if (configuration == null) // use the default one in Configuration
            Configuration = Configuration.Default;
        else
            Configuration = configuration;

        ExceptionFactory = Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    /// Gets the base path of the API client.
    /// </summary>
    /// <value>The base path</value>
    public string GetBasePath()
    {
        return Configuration.ApiClient.RestClient.Options.BaseUrl.ToString();
    }

    /// <summary>
    /// Sets the base path of the API client.
    /// </summary>
    /// <value>The base path</value>
    [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
    public void SetBasePath(string basePath)
    {
        // do nothing
    }

    /// <summary>
    /// Gets or sets the configuration object
    /// </summary>
    /// <value>An instance of the Configuration</value>
    public Configuration Configuration {get; set;}

    /// <summary>
    /// Provides a factory method hook for the creation of exceptions.
    /// </summary>
    public ExceptionFactory ExceptionFactory
    {
        get
        {
            if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
            {
                throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
            }
            return _exceptionFactory;
        }
        set { _exceptionFactory = value; }
    }

    /// <summary>
    /// Gets the default header.
    /// </summary>
    /// <returns>Dictionary of HTTP header</returns>
    [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
    public IDictionary<string, string> DefaultHeader()
    {
        return new ReadOnlyDictionary<string, string>(Configuration.DefaultHeader);
    }

    /// <summary>
    /// Add default header.
    /// </summary>
    /// <param name="key">Header field name.</param>
    /// <param name="value">Header field value.</param>
    /// <returns></returns>
    [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
    public void AddDefaultHeader(string key, string value)
    {
        Configuration.AddDefaultHeader(key, value);
    }

    /// <summary>
    /// Search bSDD using free text. Get list of Classes matching the text and optional additional filters. 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 3 characters (case and accent insensitive)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on.  For a class to be found it must be part of one of the given dictionaries (optional)</param>
    /// <param name="relatedIfcEntities">List of related IFC entities to filter on.  For a class to be found it must have at least one of the given Related Ifc Entities (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>ClassSearchResponseContractV1</returns>
    public ClassSearchResponseContractV1 ClassSearchGet (string searchText, List<string> dictionaryUris = null, List<string> relatedIfcEntities = null, int? offset = null, int? limit = null)
    {
        ApiResponse<ClassSearchResponseContractV1> localVarResponse = ClassSearchGetWithHttpInfo(searchText, dictionaryUris, relatedIfcEntities, offset, limit);
        return localVarResponse.Data;
    }

    /// <summary>
    /// Search bSDD using free text. Get list of Classes matching the text and optional additional filters. 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 3 characters (case and accent insensitive)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on.  For a class to be found it must be part of one of the given dictionaries (optional)</param>
    /// <param name="relatedIfcEntities">List of related IFC entities to filter on.  For a class to be found it must have at least one of the given Related Ifc Entities (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>ApiResponse of ClassSearchResponseContractV1</returns>
    public ApiResponse< ClassSearchResponseContractV1 > ClassSearchGetWithHttpInfo (string searchText, List<string> dictionaryUris = null, List<string> relatedIfcEntities = null, int? offset = null, int? limit = null)
    {
        // verify the required parameter 'searchText' is set
        if (searchText == null)
            throw new BsddApiException(400, "Missing required parameter 'searchText' when calling SearchApi->ClassSearchGet");

        var localVarPath = "/api/Class/Search/v1";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[] {
        };
        string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new string[] {
            "text/plain",
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "text/html",
            "text/turtle",
            "application/x-turtle",
            "application/rdf+xml"
        };
        string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (searchText != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "SearchText", searchText)); // query parameter
        if (dictionaryUris != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("multi", "DictionaryUris", dictionaryUris)); // query parameter
        if (relatedIfcEntities != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("multi", "RelatedIfcEntities", relatedIfcEntities)); // query parameter
        if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Offset", offset)); // query parameter
        if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Limit", limit)); // query parameter

        // make the HTTP request
        RestResponse localVarResponse = (RestResponse) Configuration.ApiClient.CallApi(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        int localVarStatusCode = (int) localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            Exception exception = ExceptionFactory("ClassSearchGet", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<ClassSearchResponseContractV1>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (ClassSearchResponseContractV1) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ClassSearchResponseContractV1)));
    }

    /// <summary>
    /// Search bSDD using free text. Get list of Classes matching the text and optional additional filters. 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 3 characters (case and accent insensitive)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on.  For a class to be found it must be part of one of the given dictionaries (optional)</param>
    /// <param name="relatedIfcEntities">List of related IFC entities to filter on.  For a class to be found it must have at least one of the given Related Ifc Entities (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of ClassSearchResponseContractV1</returns>
    public async Task<ClassSearchResponseContractV1> ClassSearchGetAsync (string searchText, List<string> dictionaryUris = null, List<string> relatedIfcEntities = null, int? offset = null, int? limit = null)
    {
        ApiResponse<ClassSearchResponseContractV1> localVarResponse = await ClassSearchGetAsyncWithHttpInfo(searchText, dictionaryUris, relatedIfcEntities, offset, limit);
        return localVarResponse.Data;

    }

    /// <summary>
    /// Search bSDD using free text. Get list of Classes matching the text and optional additional filters. 
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 3 characters (case and accent insensitive)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on.  For a class to be found it must be part of one of the given dictionaries (optional)</param>
    /// <param name="relatedIfcEntities">List of related IFC entities to filter on.  For a class to be found it must have at least one of the given Related Ifc Entities (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of ApiResponse (ClassSearchResponseContractV1)</returns>
    public async Task<ApiResponse<ClassSearchResponseContractV1>> ClassSearchGetAsyncWithHttpInfo (string searchText, List<string> dictionaryUris = null, List<string> relatedIfcEntities = null, int? offset = null, int? limit = null)
    {
        // verify the required parameter 'searchText' is set
        if (searchText == null)
            throw new BsddApiException(400, "Missing required parameter 'searchText' when calling SearchApi->ClassSearchGet");

        var localVarPath = "/api/Class/Search/v1";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[] {
        };
        string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new string[] {
            "text/plain",
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "text/html",
            "text/turtle",
            "application/x-turtle",
            "application/rdf+xml"
        };
        string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (searchText != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "SearchText", searchText)); // query parameter
        if (dictionaryUris != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("multi", "DictionaryUris", dictionaryUris)); // query parameter
        if (relatedIfcEntities != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("multi", "RelatedIfcEntities", relatedIfcEntities)); // query parameter
        if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Offset", offset)); // query parameter
        if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Limit", limit)); // query parameter

        // make the HTTP request
        RestResponse localVarResponse = (RestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        int localVarStatusCode = (int) localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            Exception exception = ExceptionFactory("ClassSearchGet", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<ClassSearchResponseContractV1>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (ClassSearchResponseContractV1) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ClassSearchResponseContractV1)));
    }

    /// <summary>
    /// Search the bSDD database, get list of Classes without details.  This version uses new naming and returns one Dictionary instead of a list with always one Dictionary.  This API replaces /api/SearchList. The details can be requested per Class via the Class API
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="dictionaryUri">The uri of the Dictionary to filter on (required). The \&quot;latest\&quot; option is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="searchText">The text to search for (case and accent insensitive) (optional)</param>
    /// <param name="languageCode">The ISO language code to search in and to return the text in (case sensitive)  If no language code specified or the text is not available in the requested language, the text will be returned in the default language of the dictionary.  If a language code has been given, the search takes place in texts of that language, otherwise searches will be done in the default language of the dictionary.  If an invalid or not supported language code is given, a Bad Request will be returned. (optional)</param>
    /// <param name="relatedIfcEntity">The official IFC entity name to filter on (case sensitive) (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>SearchInDictionaryResponseContractV1</returns>
    public SearchInDictionaryResponseContractV1 SearchInDictionaryGet (string dictionaryUri, string searchText = null, string languageCode = null, string relatedIfcEntity = null, int? offset = null, int? limit = null)
    {
        ApiResponse<SearchInDictionaryResponseContractV1> localVarResponse = SearchInDictionaryGetWithHttpInfo(dictionaryUri, searchText, languageCode, relatedIfcEntity, offset, limit);
        return localVarResponse.Data;
    }

    /// <summary>
    /// Search the bSDD database, get list of Classes without details.  This version uses new naming and returns one Dictionary instead of a list with always one Dictionary.  This API replaces /api/SearchList. The details can be requested per Class via the Class API
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="dictionaryUri">The uri of the Dictionary to filter on (required). The \&quot;latest\&quot; option is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="searchText">The text to search for (case and accent insensitive) (optional)</param>
    /// <param name="languageCode">The ISO language code to search in and to return the text in (case sensitive)  If no language code specified or the text is not available in the requested language, the text will be returned in the default language of the dictionary.  If a language code has been given, the search takes place in texts of that language, otherwise searches will be done in the default language of the dictionary.  If an invalid or not supported language code is given, a Bad Request will be returned. (optional)</param>
    /// <param name="relatedIfcEntity">The official IFC entity name to filter on (case sensitive) (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>ApiResponse of SearchInDictionaryResponseContractV1</returns>
    public ApiResponse< SearchInDictionaryResponseContractV1 > SearchInDictionaryGetWithHttpInfo (string dictionaryUri, string searchText = null, string languageCode = null, string relatedIfcEntity = null, int? offset = null, int? limit = null)
    {
        // verify the required parameter 'dictionaryUri' is set
        if (dictionaryUri == null)
            throw new BsddApiException(400, "Missing required parameter 'dictionaryUri' when calling SearchApi->SearchInDictionaryGet");

        var localVarPath = "/api/SearchInDictionary/v1";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[] {
        };
        string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new string[] {
            "text/plain",
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "text/html",
            "text/turtle",
            "application/x-turtle",
            "application/rdf+xml"
        };
        string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (dictionaryUri != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "DictionaryUri", dictionaryUri)); // query parameter
        if (searchText != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "SearchText", searchText)); // query parameter
        if (languageCode != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "LanguageCode", languageCode)); // query parameter
        if (relatedIfcEntity != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "RelatedIfcEntity", relatedIfcEntity)); // query parameter
        if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Offset", offset)); // query parameter
        if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Limit", limit)); // query parameter

        // make the HTTP request
        RestResponse localVarResponse = (RestResponse) Configuration.ApiClient.CallApi(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        int localVarStatusCode = (int) localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            Exception exception = ExceptionFactory("SearchInDictionaryGet", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<SearchInDictionaryResponseContractV1>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (SearchInDictionaryResponseContractV1) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SearchInDictionaryResponseContractV1)));
    }

    /// <summary>
    /// Search the bSDD database, get list of Classes without details.  This version uses new naming and returns one Dictionary instead of a list with always one Dictionary.  This API replaces /api/SearchList. The details can be requested per Class via the Class API
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="dictionaryUri">The uri of the Dictionary to filter on (required). The \&quot;latest\&quot; option is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="searchText">The text to search for (case and accent insensitive) (optional)</param>
    /// <param name="languageCode">The ISO language code to search in and to return the text in (case sensitive)  If no language code specified or the text is not available in the requested language, the text will be returned in the default language of the dictionary.  If a language code has been given, the search takes place in texts of that language, otherwise searches will be done in the default language of the dictionary.  If an invalid or not supported language code is given, a Bad Request will be returned. (optional)</param>
    /// <param name="relatedIfcEntity">The official IFC entity name to filter on (case sensitive) (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of SearchInDictionaryResponseContractV1</returns>
    public async Task<SearchInDictionaryResponseContractV1> SearchInDictionaryGetAsync (string dictionaryUri, string searchText = null, string languageCode = null, string relatedIfcEntity = null, int? offset = null, int? limit = null)
    {
        ApiResponse<SearchInDictionaryResponseContractV1> localVarResponse = await SearchInDictionaryGetAsyncWithHttpInfo(dictionaryUri, searchText, languageCode, relatedIfcEntity, offset, limit);
        return localVarResponse.Data;

    }

    /// <summary>
    /// Search the bSDD database, get list of Classes without details.  This version uses new naming and returns one Dictionary instead of a list with always one Dictionary.  This API replaces /api/SearchList. The details can be requested per Class via the Class API
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="dictionaryUri">The uri of the Dictionary to filter on (required). The \&quot;latest\&quot; option is supported, e.g. https://identifier.buildingsmart.org/uri/bs-agri/fruitvegs/latest</param>
    /// <param name="searchText">The text to search for (case and accent insensitive) (optional)</param>
    /// <param name="languageCode">The ISO language code to search in and to return the text in (case sensitive)  If no language code specified or the text is not available in the requested language, the text will be returned in the default language of the dictionary.  If a language code has been given, the search takes place in texts of that language, otherwise searches will be done in the default language of the dictionary.  If an invalid or not supported language code is given, a Bad Request will be returned. (optional)</param>
    /// <param name="relatedIfcEntity">The official IFC entity name to filter on (case sensitive) (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of ApiResponse (SearchInDictionaryResponseContractV1)</returns>
    public async Task<ApiResponse<SearchInDictionaryResponseContractV1>> SearchInDictionaryGetAsyncWithHttpInfo (string dictionaryUri, string searchText = null, string languageCode = null, string relatedIfcEntity = null, int? offset = null, int? limit = null)
    {
        // verify the required parameter 'dictionaryUri' is set
        if (dictionaryUri == null)
            throw new BsddApiException(400, "Missing required parameter 'dictionaryUri' when calling SearchApi->SearchInDictionaryGet");

        var localVarPath = "/api/SearchInDictionary/v1";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[] {
        };
        string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new string[] {
            "text/plain",
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "text/html",
            "text/turtle",
            "application/x-turtle",
            "application/rdf+xml"
        };
        string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (dictionaryUri != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "DictionaryUri", dictionaryUri)); // query parameter
        if (searchText != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "SearchText", searchText)); // query parameter
        if (languageCode != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "LanguageCode", languageCode)); // query parameter
        if (relatedIfcEntity != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "RelatedIfcEntity", relatedIfcEntity)); // query parameter
        if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Offset", offset)); // query parameter
        if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Limit", limit)); // query parameter

        // make the HTTP request
        RestResponse localVarResponse = (RestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        int localVarStatusCode = (int) localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            Exception exception = ExceptionFactory("SearchInDictionaryGet", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<SearchInDictionaryResponseContractV1>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (SearchInDictionaryResponseContractV1) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SearchInDictionaryResponseContractV1)));
    }

    /// <summary>
    /// Search bSDD using free text, get list of Classes and/or Properties.  Pagination options for Classes and Properties are combined. If result contains 10 classes and 5 properties, TotalCount will be 15. Classes will be listed first. Use Offset&#x3D;10 and Limit&#x3D;5, to get the 5 properties only. The details can be requested per Class via the Class API
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 2 characters (case and accent insensitive)</param>
    /// <param name="typeFilter">Type filter: can be \&quot;Class\&quot;, \&quot;Property\&quot;, \&quot;Material\&quot;, \&quot;GroupOfProperties\&quot; of a semicolon separated list of these. Empty means all (optional)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on (optional)</param>
    /// <param name="onlyLatestVersion"> (optional)</param>
    /// <param name="onlyVerified"> (optional)</param>
    /// <param name="includeInactive"> (optional)</param>
    /// <param name="includePreview"> (optional)</param>
    /// <param name="includeSearchDescriptions"> (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>TextSearchResponseContractV2</returns>
    public TextSearchResponseContractV2 TextSearchGet (string searchText, string typeFilter = null, List<string> dictionaryUris = null, bool? onlyLatestVersion = null, bool? onlyVerified = null, bool? includeInactive = null, bool? includePreview = null, bool? includeSearchDescriptions = null, int? offset = null, int? limit = null)
    {
        ApiResponse<TextSearchResponseContractV2> localVarResponse = TextSearchGetWithHttpInfo(searchText, typeFilter, dictionaryUris, onlyLatestVersion, onlyVerified, includeInactive, includePreview, includeSearchDescriptions, offset, limit);
        return localVarResponse.Data;
    }

    /// <summary>
    /// Search bSDD using free text, get list of Classes and/or Properties.  Pagination options for Classes and Properties are combined. If result contains 10 classes and 5 properties, TotalCount will be 15. Classes will be listed first. Use Offset&#x3D;10 and Limit&#x3D;5, to get the 5 properties only. The details can be requested per Class via the Class API
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 2 characters (case and accent insensitive)</param>
    /// <param name="typeFilter">Type filter: can be \&quot;Class\&quot;, \&quot;Property\&quot;, \&quot;Material\&quot;, \&quot;GroupOfProperties\&quot; of a semicolon separated list of these. Empty means all (optional)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on (optional)</param>
    /// <param name="onlyLatestVersion"> (optional)</param>
    /// <param name="onlyVerified"> (optional)</param>
    /// <param name="includeInactive"> (optional)</param>
    /// <param name="includePreview"> (optional)</param>
    /// <param name="includeSearchDescriptions"> (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>ApiResponse of TextSearchResponseContractV2</returns>
    public ApiResponse< TextSearchResponseContractV2 > TextSearchGetWithHttpInfo (string searchText, string typeFilter = null, List<string> dictionaryUris = null, bool? onlyLatestVersion = null, bool? onlyVerified = null, bool? includeInactive = null, bool? includePreview = null, bool? includeSearchDescriptions = null, int? offset = null, int? limit = null)
    {
        // verify the required parameter 'searchText' is set
        if (searchText == null)
            throw new BsddApiException(400, "Missing required parameter 'searchText' when calling SearchApi->TextSearchGet");

        var localVarPath = "/api/TextSearch/v2";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[] {
        };
        string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new string[] {
            "text/plain",
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "text/html",
            "text/turtle",
            "application/x-turtle",
            "application/rdf+xml"
        };
        string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (searchText != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "SearchText", searchText)); // query parameter
        if (typeFilter != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "TypeFilter", typeFilter)); // query parameter
        if (dictionaryUris != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("multi", "DictionaryUris", dictionaryUris)); // query parameter
        if (onlyLatestVersion != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "OnlyLatestVersion", onlyLatestVersion)); // query parameter
        if (onlyVerified != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "OnlyVerified", onlyVerified)); // query parameter
        if (includeInactive != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "IncludeInactive", includeInactive)); // query parameter
        if (includePreview != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "IncludePreview", includePreview)); // query parameter
        if (includeSearchDescriptions != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "IncludeSearchDescriptions", includeSearchDescriptions)); // query parameter
        if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Offset", offset)); // query parameter
        if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Limit", limit)); // query parameter

        // make the HTTP request
        RestResponse localVarResponse = (RestResponse) Configuration.ApiClient.CallApi(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        int localVarStatusCode = (int) localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            Exception exception = ExceptionFactory("TextSearchGet", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<TextSearchResponseContractV2>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (TextSearchResponseContractV2) Configuration.ApiClient.Deserialize(localVarResponse, typeof(TextSearchResponseContractV2)));
    }

    /// <summary>
    /// Search bSDD using free text, get list of Classes and/or Properties.  Pagination options for Classes and Properties are combined. If result contains 10 classes and 5 properties, TotalCount will be 15. Classes will be listed first. Use Offset&#x3D;10 and Limit&#x3D;5, to get the 5 properties only. The details can be requested per Class via the Class API
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 2 characters (case and accent insensitive)</param>
    /// <param name="typeFilter">Type filter: can be \&quot;Class\&quot;, \&quot;Property\&quot;, \&quot;Material\&quot;, \&quot;GroupOfProperties\&quot; of a semicolon separated list of these. Empty means all (optional)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on (optional)</param>
    /// <param name="onlyLatestVersion"> (optional)</param>
    /// <param name="onlyVerified"> (optional)</param>
    /// <param name="includeInactive"> (optional)</param>
    /// <param name="includePreview"> (optional)</param>
    /// <param name="includeSearchDescriptions"> (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of TextSearchResponseContractV2</returns>
    public async Task<TextSearchResponseContractV2> TextSearchGetAsync (string searchText, string typeFilter = null, List<string> dictionaryUris = null, bool? onlyLatestVersion = null, bool? onlyVerified = null, bool? includeInactive = null, bool? includePreview = null, bool? includeSearchDescriptions = null, int? offset = null, int? limit = null)
    {
        ApiResponse<TextSearchResponseContractV2> localVarResponse = await TextSearchGetAsyncWithHttpInfo(searchText, typeFilter, dictionaryUris, onlyLatestVersion, onlyVerified, includeInactive, includePreview, includeSearchDescriptions, offset, limit);
        return localVarResponse.Data;

    }

    /// <summary>
    /// Search bSDD using free text, get list of Classes and/or Properties.  Pagination options for Classes and Properties are combined. If result contains 10 classes and 5 properties, TotalCount will be 15. Classes will be listed first. Use Offset&#x3D;10 and Limit&#x3D;5, to get the 5 properties only. The details can be requested per Class via the Class API
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 2 characters (case and accent insensitive)</param>
    /// <param name="typeFilter">Type filter: can be \&quot;Class\&quot;, \&quot;Property\&quot;, \&quot;Material\&quot;, \&quot;GroupOfProperties\&quot; of a semicolon separated list of these. Empty means all (optional)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on (optional)</param>
    /// <param name="onlyLatestVersion"> (optional)</param>
    /// <param name="onlyVerified"> (optional)</param>
    /// <param name="includeInactive"> (optional)</param>
    /// <param name="includePreview"> (optional)</param>
    /// <param name="includeSearchDescriptions"> (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of ApiResponse (TextSearchResponseContractV2)</returns>
    public async Task<ApiResponse<TextSearchResponseContractV2>> TextSearchGetAsyncWithHttpInfo (string searchText, string typeFilter = null, List<string> dictionaryUris = null, bool? onlyLatestVersion = null, bool? onlyVerified = null, bool? includeInactive = null, bool? includePreview = null, bool? includeSearchDescriptions = null, int? offset = null, int? limit = null)
    {
        // verify the required parameter 'searchText' is set
        if (searchText == null)
            throw new BsddApiException(400, "Missing required parameter 'searchText' when calling SearchApi->TextSearchGet");

        var localVarPath = "/api/TextSearch/v2";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[] {
        };
        string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new string[] {
            "text/plain",
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "text/html",
            "text/turtle",
            "application/x-turtle",
            "application/rdf+xml"
        };
        string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (searchText != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "SearchText", searchText)); // query parameter
        if (typeFilter != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "TypeFilter", typeFilter)); // query parameter
        if (dictionaryUris != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("multi", "DictionaryUris", dictionaryUris)); // query parameter
        if (onlyLatestVersion != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "OnlyLatestVersion", onlyLatestVersion)); // query parameter
        if (onlyVerified != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "OnlyVerified", onlyVerified)); // query parameter
        if (includeInactive != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "IncludeInactive", includeInactive)); // query parameter
        if (includePreview != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "IncludePreview", includePreview)); // query parameter
        if (includeSearchDescriptions != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "IncludeSearchDescriptions", includeSearchDescriptions)); // query parameter
        if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Offset", offset)); // query parameter
        if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Limit", limit)); // query parameter

        // make the HTTP request
        RestResponse localVarResponse = (RestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        int localVarStatusCode = (int) localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            Exception exception = ExceptionFactory("TextSearchGet", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<TextSearchResponseContractV2>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (TextSearchResponseContractV2) Configuration.ApiClient.Deserialize(localVarResponse, typeof(TextSearchResponseContractV2)));
    }

    /// <summary>
    /// Search bSDD using free text, get list of Classes and/or Properties.  Pagination options for Classes and Properties are combined. If result contains 10 classes and 5 properties, TotalCount will be 15. Classes will be listed first. Use Offset&#x3D;10 and Limit&#x3D;5, to get the 5 properties only. The details can be requested per Class via the Class API
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 2 characters (case and accent insensitive)</param>
    /// <param name="typeFilter">Type filter: must be \&quot;All\&quot;, \&quot;Classes\&quot; or \&quot;Properties\&quot; (optional)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>TextSearchResponseContractV1</returns>
    public TextSearchResponseContractV1 TextSearchV1Get (string searchText, string typeFilter = null, List<string> dictionaryUris = null, int? offset = null, int? limit = null)
    {
        ApiResponse<TextSearchResponseContractV1> localVarResponse = TextSearchV1GetWithHttpInfo(searchText, typeFilter, dictionaryUris, offset, limit);
        return localVarResponse.Data;
    }

    /// <summary>
    /// Search bSDD using free text, get list of Classes and/or Properties.  Pagination options for Classes and Properties are combined. If result contains 10 classes and 5 properties, TotalCount will be 15. Classes will be listed first. Use Offset&#x3D;10 and Limit&#x3D;5, to get the 5 properties only. The details can be requested per Class via the Class API
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 2 characters (case and accent insensitive)</param>
    /// <param name="typeFilter">Type filter: must be \&quot;All\&quot;, \&quot;Classes\&quot; or \&quot;Properties\&quot; (optional)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>ApiResponse of TextSearchResponseContractV1</returns>
    public ApiResponse< TextSearchResponseContractV1 > TextSearchV1GetWithHttpInfo (string searchText, string typeFilter = null, List<string> dictionaryUris = null, int? offset = null, int? limit = null)
    {
        // verify the required parameter 'searchText' is set
        if (searchText == null)
            throw new BsddApiException(400, "Missing required parameter 'searchText' when calling SearchApi->TextSearchV1Get");

        var localVarPath = "/api/TextSearch/v1";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[] {
        };
        string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new string[] {
            "text/plain",
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "text/html",
            "text/turtle",
            "application/x-turtle",
            "application/rdf+xml"
        };
        string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (searchText != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "SearchText", searchText)); // query parameter
        if (typeFilter != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "TypeFilter", typeFilter)); // query parameter
        if (dictionaryUris != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("multi", "DictionaryUris", dictionaryUris)); // query parameter
        if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Offset", offset)); // query parameter
        if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Limit", limit)); // query parameter

        // make the HTTP request
        RestResponse localVarResponse = (RestResponse) Configuration.ApiClient.CallApi(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        int localVarStatusCode = (int) localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            Exception exception = ExceptionFactory("TextSearchV1Get", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<TextSearchResponseContractV1>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (TextSearchResponseContractV1) Configuration.ApiClient.Deserialize(localVarResponse, typeof(TextSearchResponseContractV1)));
    }

    /// <summary>
    /// Search bSDD using free text, get list of Classes and/or Properties.  Pagination options for Classes and Properties are combined. If result contains 10 classes and 5 properties, TotalCount will be 15. Classes will be listed first. Use Offset&#x3D;10 and Limit&#x3D;5, to get the 5 properties only. The details can be requested per Class via the Class API
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 2 characters (case and accent insensitive)</param>
    /// <param name="typeFilter">Type filter: must be \&quot;All\&quot;, \&quot;Classes\&quot; or \&quot;Properties\&quot; (optional)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of TextSearchResponseContractV1</returns>
    public async Task<TextSearchResponseContractV1> TextSearchV1GetAsync (string searchText, string typeFilter = null, List<string> dictionaryUris = null, int? offset = null, int? limit = null)
    {
        ApiResponse<TextSearchResponseContractV1> localVarResponse = await TextSearchV1GetAsyncWithHttpInfo(searchText, typeFilter, dictionaryUris, offset, limit);
        return localVarResponse.Data;

    }

    /// <summary>
    /// Search bSDD using free text, get list of Classes and/or Properties.  Pagination options for Classes and Properties are combined. If result contains 10 classes and 5 properties, TotalCount will be 15. Classes will be listed first. Use Offset&#x3D;10 and Limit&#x3D;5, to get the 5 properties only. The details can be requested per Class via the Class API
    /// </summary>
    /// <exception cref="BsddApiException">Thrown when fails to make API call</exception>
    /// <param name="searchText">The text to search for, minimum 2 characters (case and accent insensitive)</param>
    /// <param name="typeFilter">Type filter: must be \&quot;All\&quot;, \&quot;Classes\&quot; or \&quot;Properties\&quot; (optional)</param>
    /// <param name="dictionaryUris">List of dictionaries to filter on (optional)</param>
    /// <param name="offset">Zero-based offset of the first item to be returned. Default is 0. (optional)</param>
    /// <param name="limit">Limit number of items to be returned. The default and maximum number of items returned is 1000. When Offset is specified, then the default limit is 100. (optional)</param>
    /// <returns>Task of ApiResponse (TextSearchResponseContractV1)</returns>
    public async Task<ApiResponse<TextSearchResponseContractV1>> TextSearchV1GetAsyncWithHttpInfo (string searchText, string typeFilter = null, List<string> dictionaryUris = null, int? offset = null, int? limit = null)
    {
        // verify the required parameter 'searchText' is set
        if (searchText == null)
            throw new BsddApiException(400, "Missing required parameter 'searchText' when calling SearchApi->TextSearchV1Get");

        var localVarPath = "/api/TextSearch/v1";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[] {
        };
        string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new string[] {
            "text/plain",
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "text/html",
            "text/turtle",
            "application/x-turtle",
            "application/rdf+xml"
        };
        string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (searchText != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "SearchText", searchText)); // query parameter
        if (typeFilter != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "TypeFilter", typeFilter)); // query parameter
        if (dictionaryUris != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("multi", "DictionaryUris", dictionaryUris)); // query parameter
        if (offset != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Offset", offset)); // query parameter
        if (limit != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "Limit", limit)); // query parameter

        // make the HTTP request
        RestResponse localVarResponse = (RestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        int localVarStatusCode = (int) localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            Exception exception = ExceptionFactory("TextSearchV1Get", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<TextSearchResponseContractV1>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (TextSearchResponseContractV1) Configuration.ApiClient.Deserialize(localVarResponse, typeof(TextSearchResponseContractV1)));
    }

}