/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ConsoleDemo.Model;

/// <summary>
/// ClassContractV1
/// </summary>
[DataContract]
public partial class ClassContractV1 :  IEquatable<ClassContractV1>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ClassContractV1" /> class.
    /// </summary>
    /// <param name="dictionaryUri">URI of the dictionary.</param>
    /// <param name="activationDateUtc">Date of activation (required).</param>
    /// <param name="code">Code used originally by the dictionary (required).</param>
    /// <param name="creatorLanguageCode">Language code of the creator.</param>
    /// <param name="countriesOfUse">List of countries where used.</param>
    /// <param name="countryOfOrigin">Country of origin.</param>
    /// <param name="deActivationDateUtc">Date of deactivation.</param>
    /// <param name="definition">Formal definition.</param>
    /// <param name="deprecationExplanation">Explanation of the deprecation.</param>
    /// <param name="description">Description.</param>
    /// <param name="documentReference">Reference to a(n official) document.</param>
    /// <param name="name">Name (required).</param>
    /// <param name="uri">Unique identification (required).</param>
    /// <param name="replacedObjectCodes">List of codes of the replaced items.</param>
    /// <param name="replacingObjectCodes">List of codes of the replacing items.</param>
    /// <param name="revisionDateUtc">Date of the revision.</param>
    /// <param name="revisionNumber">Revision number.</param>
    /// <param name="status">Status, can be: Preview, Active or Inactive (required).</param>
    /// <param name="subdivisionsOfUse">List of subdivisions (e.g. states) where used.</param>
    /// <param name="uid">Alternative unique global identification.</param>
    /// <param name="versionDateUtc">Date of the version (required).</param>
    /// <param name="versionNumber">Version number.</param>
    /// <param name="visualRepresentationUri">URI of a visual representation.</param>
    /// <param name="classType">Type of Class.</param>
    /// <param name="referenceCode">Code that can be used for dictionary specific purposes.</param>
    /// <param name="synonyms">List of synonyms for the class.</param>
    /// <param name="relatedIfcEntityNames">List of related IFC entity names (version independent).</param>
    /// <param name="parentClassReference">parentClassReference.</param>
    /// <param name="classProperties">List of the properties of this class.</param>
    /// <param name="classRelations">List of relations to other classes, can be reference to classes of other dictionaries.</param>
    /// <param name="childClassReferences">List of child classes (only filled if requested).</param>
    /// <param name="reverseClassRelations">List of relations of other classes to this class (only filled if requested).</param>
    /// <param name="hierarchy">List of parents of this class till root.</param>
    public ClassContractV1(string dictionaryUri = default(string), DateTime? activationDateUtc = default(DateTime?), string code = default(string), string creatorLanguageCode = default(string), List<string> countriesOfUse = default(List<string>), string countryOfOrigin = default(string), DateTime? deActivationDateUtc = default(DateTime?), string definition = default(string), string deprecationExplanation = default(string), string description = default(string), string documentReference = default(string), string name = default(string), string uri = default(string), List<string> replacedObjectCodes = default(List<string>), List<string> replacingObjectCodes = default(List<string>), DateTime? revisionDateUtc = default(DateTime?), int? revisionNumber = default(int?), string status = default(string), List<string> subdivisionsOfUse = default(List<string>), string uid = default(string), DateTime? versionDateUtc = default(DateTime?), int? versionNumber = default(int?), string visualRepresentationUri = default(string), string classType = default(string), string referenceCode = default(string), List<string> synonyms = default(List<string>), List<string> relatedIfcEntityNames = default(List<string>), ClassReferenceContractV1 parentClassReference = default(ClassReferenceContractV1), List<ClassPropertyContractV1> classProperties = default(List<ClassPropertyContractV1>), List<ClassRelationContractV1> classRelations = default(List<ClassRelationContractV1>), List<ClassReferenceContractV1> childClassReferences = default(List<ClassReferenceContractV1>), List<ClassReverseRelationContractV1> reverseClassRelations = default(List<ClassReverseRelationContractV1>), List<HierarchyItemContractV1> hierarchy = default(List<HierarchyItemContractV1>))
    {
        // to ensure "activationDateUtc" is required (not null)
        if (activationDateUtc == null)
        {
            throw new InvalidDataException("activationDateUtc is a required property for ClassContractV1 and cannot be null");
        }
        else
        {
            this.ActivationDateUtc = activationDateUtc;
        }
        // to ensure "code" is required (not null)
        if (string.IsNullOrWhiteSpace(code))
        {
            throw new InvalidDataException("code is a required property for ClassContractV1 and cannot be null");
        }
        else
        {
            this.Code = code;
        }
        // to ensure "name" is required (not null)
        if (name == null)
        {
            throw new InvalidDataException("name is a required property for ClassContractV1 and cannot be null");
        }
        else
        {
            this.Name = name;
        }
        // to ensure "uri" is required (not null)
        if (uri == null)
        {
            throw new InvalidDataException("uri is a required property for ClassContractV1 and cannot be null");
        }
        else
        {
            this.Uri = uri;
        }
        // to ensure "status" is required (not null)
        if (status == null)
        {
            throw new InvalidDataException("status is a required property for ClassContractV1 and cannot be null");
        }
        else
        {
            this.Status = status;
        }
        // to ensure "versionDateUtc" is required (not null)
        if (versionDateUtc == null)
        {
            throw new InvalidDataException("versionDateUtc is a required property for ClassContractV1 and cannot be null");
        }
        else
        {
            this.VersionDateUtc = versionDateUtc;
        }
        this.DictionaryUri = dictionaryUri;
        this.CreatorLanguageCode = creatorLanguageCode;
        this.CountriesOfUse = countriesOfUse;
        this.CountryOfOrigin = countryOfOrigin;
        this.DeActivationDateUtc = deActivationDateUtc;
        this.Definition = definition;
        this.DeprecationExplanation = deprecationExplanation;
        this.Description = description;
        this.DocumentReference = documentReference;
        this.ReplacedObjectCodes = replacedObjectCodes;
        this.ReplacingObjectCodes = replacingObjectCodes;
        this.RevisionDateUtc = revisionDateUtc;
        this.RevisionNumber = revisionNumber;
        this.SubdivisionsOfUse = subdivisionsOfUse;
        this.Uid = uid;
        this.VersionNumber = versionNumber;
        this.VisualRepresentationUri = visualRepresentationUri;
        this.ClassType = classType;
        this.ReferenceCode = referenceCode;
        this.Synonyms = synonyms;
        this.RelatedIfcEntityNames = relatedIfcEntityNames;
        this.ParentClassReference = parentClassReference;
        this.ClassProperties = classProperties;
        this.ClassRelations = classRelations;
        this.ChildClassReferences = childClassReferences;
        this.ReverseClassRelations = reverseClassRelations;
        this.Hierarchy = hierarchy;
    }
        
    /// <summary>
    /// URI of the dictionary
    /// </summary>
    /// <value>URI of the dictionary</value>
    [DataMember(Name="dictionaryUri", EmitDefaultValue=false)]
    public string DictionaryUri { get; set; }

    /// <summary>
    /// Date of activation
    /// </summary>
    /// <value>Date of activation</value>
    [DataMember(Name="activationDateUtc", EmitDefaultValue=false)]
    public DateTime? ActivationDateUtc { get; set; }

    /// <summary>
    /// Code used originally by the dictionary
    /// </summary>
    /// <value>Code used originally by the dictionary</value>
    [DataMember(Name="code", EmitDefaultValue=false)]
    public string Code { get; set; }

    /// <summary>
    /// Language code of the creator
    /// </summary>
    /// <value>Language code of the creator</value>
    [DataMember(Name="creatorLanguageCode", EmitDefaultValue=false)]
    public string CreatorLanguageCode { get; set; }

    /// <summary>
    /// List of countries where used
    /// </summary>
    /// <value>List of countries where used</value>
    [DataMember(Name="countriesOfUse", EmitDefaultValue=false)]
    public List<string> CountriesOfUse { get; set; }

    /// <summary>
    /// Country of origin
    /// </summary>
    /// <value>Country of origin</value>
    [DataMember(Name="countryOfOrigin", EmitDefaultValue=false)]
    public string CountryOfOrigin { get; set; }

    /// <summary>
    /// Date of deactivation
    /// </summary>
    /// <value>Date of deactivation</value>
    [DataMember(Name="deActivationDateUtc", EmitDefaultValue=false)]
    public DateTime? DeActivationDateUtc { get; set; }

    /// <summary>
    /// Formal definition
    /// </summary>
    /// <value>Formal definition</value>
    [DataMember(Name="definition", EmitDefaultValue=false)]
    public string Definition { get; set; }

    /// <summary>
    /// Explanation of the deprecation
    /// </summary>
    /// <value>Explanation of the deprecation</value>
    [DataMember(Name="deprecationExplanation", EmitDefaultValue=false)]
    public string DeprecationExplanation { get; set; }

    /// <summary>
    /// Description
    /// </summary>
    /// <value>Description</value>
    [DataMember(Name="description", EmitDefaultValue=false)]
    public string Description { get; set; }

    /// <summary>
    /// Reference to a(n official) document
    /// </summary>
    /// <value>Reference to a(n official) document</value>
    [DataMember(Name="documentReference", EmitDefaultValue=false)]
    public string DocumentReference { get; set; }

    /// <summary>
    /// Name
    /// </summary>
    /// <value>Name</value>
    [DataMember(Name="name", EmitDefaultValue=false)]
    public string Name { get; set; }

    /// <summary>
    /// Unique identification
    /// </summary>
    /// <value>Unique identification</value>
    [DataMember(Name="uri", EmitDefaultValue=false)]
    public string Uri { get; set; }

    /// <summary>
    /// List of codes of the replaced items
    /// </summary>
    /// <value>List of codes of the replaced items</value>
    [DataMember(Name="replacedObjectCodes", EmitDefaultValue=false)]
    public List<string> ReplacedObjectCodes { get; set; }

    /// <summary>
    /// List of codes of the replacing items
    /// </summary>
    /// <value>List of codes of the replacing items</value>
    [DataMember(Name="replacingObjectCodes", EmitDefaultValue=false)]
    public List<string> ReplacingObjectCodes { get; set; }

    /// <summary>
    /// Date of the revision
    /// </summary>
    /// <value>Date of the revision</value>
    [DataMember(Name="revisionDateUtc", EmitDefaultValue=false)]
    public DateTime? RevisionDateUtc { get; set; }

    /// <summary>
    /// Revision number
    /// </summary>
    /// <value>Revision number</value>
    [DataMember(Name="revisionNumber", EmitDefaultValue=false)]
    public int? RevisionNumber { get; set; }

    /// <summary>
    /// Status, can be: Preview, Active or Inactive
    /// </summary>
    /// <value>Status, can be: Preview, Active or Inactive</value>
    [DataMember(Name="status", EmitDefaultValue=false)]
    public string Status { get; set; }

    /// <summary>
    /// List of subdivisions (e.g. states) where used
    /// </summary>
    /// <value>List of subdivisions (e.g. states) where used</value>
    [DataMember(Name="subdivisionsOfUse", EmitDefaultValue=false)]
    public List<string> SubdivisionsOfUse { get; set; }

    /// <summary>
    /// Alternative unique global identification
    /// </summary>
    /// <value>Alternative unique global identification</value>
    [DataMember(Name="uid", EmitDefaultValue=false)]
    public string Uid { get; set; }

    /// <summary>
    /// Date of the version
    /// </summary>
    /// <value>Date of the version</value>
    [DataMember(Name="versionDateUtc", EmitDefaultValue=false)]
    public DateTime? VersionDateUtc { get; set; }

    /// <summary>
    /// Version number
    /// </summary>
    /// <value>Version number</value>
    [DataMember(Name="versionNumber", EmitDefaultValue=false)]
    public int? VersionNumber { get; set; }

    /// <summary>
    /// URI of a visual representation
    /// </summary>
    /// <value>URI of a visual representation</value>
    [DataMember(Name="visualRepresentationUri", EmitDefaultValue=false)]
    public string VisualRepresentationUri { get; set; }

    /// <summary>
    /// Type of Class
    /// </summary>
    /// <value>Type of Class</value>
    [DataMember(Name="classType", EmitDefaultValue=false)]
    public string ClassType { get; set; }

    /// <summary>
    /// Code that can be used for dictionary specific purposes
    /// </summary>
    /// <value>Code that can be used for dictionary specific purposes</value>
    [DataMember(Name="referenceCode", EmitDefaultValue=false)]
    public string ReferenceCode { get; set; }

    /// <summary>
    /// List of synonyms for the class
    /// </summary>
    /// <value>List of synonyms for the class</value>
    [DataMember(Name="synonyms", EmitDefaultValue=false)]
    public List<string> Synonyms { get; set; }

    /// <summary>
    /// List of related IFC entity names (version independent)
    /// </summary>
    /// <value>List of related IFC entity names (version independent)</value>
    [DataMember(Name="relatedIfcEntityNames", EmitDefaultValue=false)]
    public List<string> RelatedIfcEntityNames { get; set; }

    /// <summary>
    /// Gets or Sets ParentClassReference
    /// </summary>
    [DataMember(Name="parentClassReference", EmitDefaultValue=false)]
    public ClassReferenceContractV1 ParentClassReference { get; set; }

    /// <summary>
    /// List of the properties of this class
    /// </summary>
    /// <value>List of the properties of this class</value>
    [DataMember(Name="classProperties", EmitDefaultValue=false)]
    public List<ClassPropertyContractV1> ClassProperties { get; set; }

    /// <summary>
    /// List of relations to other classes, can be reference to classes of other dictionaries
    /// </summary>
    /// <value>List of relations to other classes, can be reference to classes of other dictionaries</value>
    [DataMember(Name="classRelations", EmitDefaultValue=false)]
    public List<ClassRelationContractV1> ClassRelations { get; set; }

    /// <summary>
    /// List of child classes (only filled if requested)
    /// </summary>
    /// <value>List of child classes (only filled if requested)</value>
    [DataMember(Name="childClassReferences", EmitDefaultValue=false)]
    public List<ClassReferenceContractV1> ChildClassReferences { get; set; }

    /// <summary>
    /// List of relations of other classes to this class (only filled if requested)
    /// </summary>
    /// <value>List of relations of other classes to this class (only filled if requested)</value>
    [DataMember(Name="reverseClassRelations", EmitDefaultValue=false)]
    public List<ClassReverseRelationContractV1> ReverseClassRelations { get; set; }

    /// <summary>
    /// List of parents of this class till root
    /// </summary>
    /// <value>List of parents of this class till root</value>
    [DataMember(Name="hierarchy", EmitDefaultValue=false)]
    public List<HierarchyItemContractV1> Hierarchy { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class ClassContractV1 {\n");
        sb.Append("  DictionaryUri: ").Append(DictionaryUri).Append("\n");
        sb.Append("  ActivationDateUtc: ").Append(ActivationDateUtc).Append("\n");
        sb.Append("  Code: ").Append(Code).Append("\n");
        sb.Append("  CreatorLanguageCode: ").Append(CreatorLanguageCode).Append("\n");
        sb.Append("  CountriesOfUse: ").Append(CountriesOfUse).Append("\n");
        sb.Append("  CountryOfOrigin: ").Append(CountryOfOrigin).Append("\n");
        sb.Append("  DeActivationDateUtc: ").Append(DeActivationDateUtc).Append("\n");
        sb.Append("  Definition: ").Append(Definition).Append("\n");
        sb.Append("  DeprecationExplanation: ").Append(DeprecationExplanation).Append("\n");
        sb.Append("  Description: ").Append(Description).Append("\n");
        sb.Append("  DocumentReference: ").Append(DocumentReference).Append("\n");
        sb.Append("  Name: ").Append(Name).Append("\n");
        sb.Append("  Uri: ").Append(Uri).Append("\n");
        sb.Append("  ReplacedObjectCodes: ").Append(ReplacedObjectCodes).Append("\n");
        sb.Append("  ReplacingObjectCodes: ").Append(ReplacingObjectCodes).Append("\n");
        sb.Append("  RevisionDateUtc: ").Append(RevisionDateUtc).Append("\n");
        sb.Append("  RevisionNumber: ").Append(RevisionNumber).Append("\n");
        sb.Append("  Status: ").Append(Status).Append("\n");
        sb.Append("  SubdivisionsOfUse: ").Append(SubdivisionsOfUse).Append("\n");
        sb.Append("  Uid: ").Append(Uid).Append("\n");
        sb.Append("  VersionDateUtc: ").Append(VersionDateUtc).Append("\n");
        sb.Append("  VersionNumber: ").Append(VersionNumber).Append("\n");
        sb.Append("  VisualRepresentationUri: ").Append(VisualRepresentationUri).Append("\n");
        sb.Append("  ClassType: ").Append(ClassType).Append("\n");
        sb.Append("  ReferenceCode: ").Append(ReferenceCode).Append("\n");
        sb.Append("  Synonyms: ").Append(Synonyms).Append("\n");
        sb.Append("  RelatedIfcEntityNames: ").Append(RelatedIfcEntityNames).Append("\n");
        sb.Append("  ParentClassReference: ").Append(ParentClassReference).Append("\n");
        sb.Append("  ClassProperties: ").Append(ClassProperties).Append("\n");
        sb.Append("  ClassRelations: ").Append(ClassRelations).Append("\n");
        sb.Append("  ChildClassReferences: ").Append(ChildClassReferences).Append("\n");
        sb.Append("  ReverseClassRelations: ").Append(ReverseClassRelations).Append("\n");
        sb.Append("  Hierarchy: ").Append(Hierarchy).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }
  
    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return this.Equals(input as ClassContractV1);
    }

    /// <summary>
    /// Returns true if ClassContractV1 instances are equal
    /// </summary>
    /// <param name="input">Instance of ClassContractV1 to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(ClassContractV1 input)
    {
        if (input == null)
            return false;

        return 
            (
                this.DictionaryUri == input.DictionaryUri ||
                (this.DictionaryUri != null &&
                 this.DictionaryUri.Equals(input.DictionaryUri))
            ) && 
            (
                this.ActivationDateUtc == input.ActivationDateUtc ||
                (this.ActivationDateUtc != null &&
                 this.ActivationDateUtc.Equals(input.ActivationDateUtc))
            ) && 
            (
                this.Code == input.Code ||
                (this.Code != null &&
                 this.Code.Equals(input.Code))
            ) && 
            (
                this.CreatorLanguageCode == input.CreatorLanguageCode ||
                (this.CreatorLanguageCode != null &&
                 this.CreatorLanguageCode.Equals(input.CreatorLanguageCode))
            ) && 
            (
                this.CountriesOfUse == input.CountriesOfUse ||
                this.CountriesOfUse != null &&
                input.CountriesOfUse != null &&
                this.CountriesOfUse.SequenceEqual(input.CountriesOfUse)
            ) && 
            (
                this.CountryOfOrigin == input.CountryOfOrigin ||
                (this.CountryOfOrigin != null &&
                 this.CountryOfOrigin.Equals(input.CountryOfOrigin))
            ) && 
            (
                this.DeActivationDateUtc == input.DeActivationDateUtc ||
                (this.DeActivationDateUtc != null &&
                 this.DeActivationDateUtc.Equals(input.DeActivationDateUtc))
            ) && 
            (
                this.Definition == input.Definition ||
                (this.Definition != null &&
                 this.Definition.Equals(input.Definition))
            ) && 
            (
                this.DeprecationExplanation == input.DeprecationExplanation ||
                (this.DeprecationExplanation != null &&
                 this.DeprecationExplanation.Equals(input.DeprecationExplanation))
            ) && 
            (
                this.Description == input.Description ||
                (this.Description != null &&
                 this.Description.Equals(input.Description))
            ) && 
            (
                this.DocumentReference == input.DocumentReference ||
                (this.DocumentReference != null &&
                 this.DocumentReference.Equals(input.DocumentReference))
            ) && 
            (
                this.Name == input.Name ||
                (this.Name != null &&
                 this.Name.Equals(input.Name))
            ) && 
            (
                this.Uri == input.Uri ||
                (this.Uri != null &&
                 this.Uri.Equals(input.Uri))
            ) && 
            (
                this.ReplacedObjectCodes == input.ReplacedObjectCodes ||
                this.ReplacedObjectCodes != null &&
                input.ReplacedObjectCodes != null &&
                this.ReplacedObjectCodes.SequenceEqual(input.ReplacedObjectCodes)
            ) && 
            (
                this.ReplacingObjectCodes == input.ReplacingObjectCodes ||
                this.ReplacingObjectCodes != null &&
                input.ReplacingObjectCodes != null &&
                this.ReplacingObjectCodes.SequenceEqual(input.ReplacingObjectCodes)
            ) && 
            (
                this.RevisionDateUtc == input.RevisionDateUtc ||
                (this.RevisionDateUtc != null &&
                 this.RevisionDateUtc.Equals(input.RevisionDateUtc))
            ) && 
            (
                this.RevisionNumber == input.RevisionNumber ||
                (this.RevisionNumber != null &&
                 this.RevisionNumber.Equals(input.RevisionNumber))
            ) && 
            (
                this.Status == input.Status ||
                (this.Status != null &&
                 this.Status.Equals(input.Status))
            ) && 
            (
                this.SubdivisionsOfUse == input.SubdivisionsOfUse ||
                this.SubdivisionsOfUse != null &&
                input.SubdivisionsOfUse != null &&
                this.SubdivisionsOfUse.SequenceEqual(input.SubdivisionsOfUse)
            ) && 
            (
                this.Uid == input.Uid ||
                (this.Uid != null &&
                 this.Uid.Equals(input.Uid))
            ) && 
            (
                this.VersionDateUtc == input.VersionDateUtc ||
                (this.VersionDateUtc != null &&
                 this.VersionDateUtc.Equals(input.VersionDateUtc))
            ) && 
            (
                this.VersionNumber == input.VersionNumber ||
                (this.VersionNumber != null &&
                 this.VersionNumber.Equals(input.VersionNumber))
            ) && 
            (
                this.VisualRepresentationUri == input.VisualRepresentationUri ||
                (this.VisualRepresentationUri != null &&
                 this.VisualRepresentationUri.Equals(input.VisualRepresentationUri))
            ) && 
            (
                this.ClassType == input.ClassType ||
                (this.ClassType != null &&
                 this.ClassType.Equals(input.ClassType))
            ) && 
            (
                this.ReferenceCode == input.ReferenceCode ||
                (this.ReferenceCode != null &&
                 this.ReferenceCode.Equals(input.ReferenceCode))
            ) && 
            (
                this.Synonyms == input.Synonyms ||
                this.Synonyms != null &&
                input.Synonyms != null &&
                this.Synonyms.SequenceEqual(input.Synonyms)
            ) && 
            (
                this.RelatedIfcEntityNames == input.RelatedIfcEntityNames ||
                this.RelatedIfcEntityNames != null &&
                input.RelatedIfcEntityNames != null &&
                this.RelatedIfcEntityNames.SequenceEqual(input.RelatedIfcEntityNames)
            ) && 
            (
                this.ParentClassReference == input.ParentClassReference ||
                (this.ParentClassReference != null &&
                 this.ParentClassReference.Equals(input.ParentClassReference))
            ) && 
            (
                this.ClassProperties == input.ClassProperties ||
                this.ClassProperties != null &&
                input.ClassProperties != null &&
                this.ClassProperties.SequenceEqual(input.ClassProperties)
            ) && 
            (
                this.ClassRelations == input.ClassRelations ||
                this.ClassRelations != null &&
                input.ClassRelations != null &&
                this.ClassRelations.SequenceEqual(input.ClassRelations)
            ) && 
            (
                this.ChildClassReferences == input.ChildClassReferences ||
                this.ChildClassReferences != null &&
                input.ChildClassReferences != null &&
                this.ChildClassReferences.SequenceEqual(input.ChildClassReferences)
            ) && 
            (
                this.ReverseClassRelations == input.ReverseClassRelations ||
                this.ReverseClassRelations != null &&
                input.ReverseClassRelations != null &&
                this.ReverseClassRelations.SequenceEqual(input.ReverseClassRelations)
            ) && 
            (
                this.Hierarchy == input.Hierarchy ||
                this.Hierarchy != null &&
                input.Hierarchy != null &&
                this.Hierarchy.SequenceEqual(input.Hierarchy)
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (this.DictionaryUri != null)
                hashCode = hashCode * 59 + this.DictionaryUri.GetHashCode();
            if (this.ActivationDateUtc != null)
                hashCode = hashCode * 59 + this.ActivationDateUtc.GetHashCode();
            if (this.Code != null)
                hashCode = hashCode * 59 + this.Code.GetHashCode();
            if (this.CreatorLanguageCode != null)
                hashCode = hashCode * 59 + this.CreatorLanguageCode.GetHashCode();
            if (this.CountriesOfUse != null)
                hashCode = hashCode * 59 + this.CountriesOfUse.GetHashCode();
            if (this.CountryOfOrigin != null)
                hashCode = hashCode * 59 + this.CountryOfOrigin.GetHashCode();
            if (this.DeActivationDateUtc != null)
                hashCode = hashCode * 59 + this.DeActivationDateUtc.GetHashCode();
            if (this.Definition != null)
                hashCode = hashCode * 59 + this.Definition.GetHashCode();
            if (this.DeprecationExplanation != null)
                hashCode = hashCode * 59 + this.DeprecationExplanation.GetHashCode();
            if (this.Description != null)
                hashCode = hashCode * 59 + this.Description.GetHashCode();
            if (this.DocumentReference != null)
                hashCode = hashCode * 59 + this.DocumentReference.GetHashCode();
            if (this.Name != null)
                hashCode = hashCode * 59 + this.Name.GetHashCode();
            if (this.Uri != null)
                hashCode = hashCode * 59 + this.Uri.GetHashCode();
            if (this.ReplacedObjectCodes != null)
                hashCode = hashCode * 59 + this.ReplacedObjectCodes.GetHashCode();
            if (this.ReplacingObjectCodes != null)
                hashCode = hashCode * 59 + this.ReplacingObjectCodes.GetHashCode();
            if (this.RevisionDateUtc != null)
                hashCode = hashCode * 59 + this.RevisionDateUtc.GetHashCode();
            if (this.RevisionNumber != null)
                hashCode = hashCode * 59 + this.RevisionNumber.GetHashCode();
            if (this.Status != null)
                hashCode = hashCode * 59 + this.Status.GetHashCode();
            if (this.SubdivisionsOfUse != null)
                hashCode = hashCode * 59 + this.SubdivisionsOfUse.GetHashCode();
            if (this.Uid != null)
                hashCode = hashCode * 59 + this.Uid.GetHashCode();
            if (this.VersionDateUtc != null)
                hashCode = hashCode * 59 + this.VersionDateUtc.GetHashCode();
            if (this.VersionNumber != null)
                hashCode = hashCode * 59 + this.VersionNumber.GetHashCode();
            if (this.VisualRepresentationUri != null)
                hashCode = hashCode * 59 + this.VisualRepresentationUri.GetHashCode();
            if (this.ClassType != null)
                hashCode = hashCode * 59 + this.ClassType.GetHashCode();
            if (this.ReferenceCode != null)
                hashCode = hashCode * 59 + this.ReferenceCode.GetHashCode();
            if (this.Synonyms != null)
                hashCode = hashCode * 59 + this.Synonyms.GetHashCode();
            if (this.RelatedIfcEntityNames != null)
                hashCode = hashCode * 59 + this.RelatedIfcEntityNames.GetHashCode();
            if (this.ParentClassReference != null)
                hashCode = hashCode * 59 + this.ParentClassReference.GetHashCode();
            if (this.ClassProperties != null)
                hashCode = hashCode * 59 + this.ClassProperties.GetHashCode();
            if (this.ClassRelations != null)
                hashCode = hashCode * 59 + this.ClassRelations.GetHashCode();
            if (this.ChildClassReferences != null)
                hashCode = hashCode * 59 + this.ChildClassReferences.GetHashCode();
            if (this.ReverseClassRelations != null)
                hashCode = hashCode * 59 + this.ReverseClassRelations.GetHashCode();
            if (this.Hierarchy != null)
                hashCode = hashCode * 59 + this.Hierarchy.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}