/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ConsoleDemo.Model;

/// <summary>
/// ClassListItemContractV1Classes
/// </summary>
[DataContract]
public partial class ClassListItemContractV1Classes :  IEquatable<ClassListItemContractV1Classes>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ClassListItemContractV1Classes" /> class.
    /// </summary>
    /// <param name="uri">uri.</param>
    /// <param name="code">code.</param>
    /// <param name="name">name.</param>
    /// <param name="classType">classType.</param>
    /// <param name="referenceCode">referenceCode.</param>
    /// <param name="parentClassCode">parentClassCode.</param>
    /// <param name="descriptionPart">Description of the class, max 101 characters long.</param>
    /// <param name="children">children.</param>
    public ClassListItemContractV1Classes(string uri = default(string), string code = default(string), string name = default(string), string classType = default(string), string referenceCode = default(string), string parentClassCode = default(string), string descriptionPart = default(string), List<ClassListItemContractV1Classes> children = default(List<ClassListItemContractV1Classes>))
    {
        this.Uri = uri;
        this.Code = code;
        this.Name = name;
        this.ClassType = classType;
        this.ReferenceCode = referenceCode;
        this.ParentClassCode = parentClassCode;
        this.DescriptionPart = descriptionPart;
        this.Children = children;
    }
        
    /// <summary>
    /// Gets or Sets Uri
    /// </summary>
    [DataMember(Name="uri", EmitDefaultValue=false)]
    public string Uri { get; set; }

    /// <summary>
    /// Gets or Sets Code
    /// </summary>
    [DataMember(Name="code", EmitDefaultValue=false)]
    public string Code { get; set; }

    /// <summary>
    /// Gets or Sets Name
    /// </summary>
    [DataMember(Name="name", EmitDefaultValue=false)]
    public string Name { get; set; }

    /// <summary>
    /// Gets or Sets ClassType
    /// </summary>
    [DataMember(Name="classType", EmitDefaultValue=false)]
    public string ClassType { get; set; }

    /// <summary>
    /// Gets or Sets ReferenceCode
    /// </summary>
    [DataMember(Name="referenceCode", EmitDefaultValue=false)]
    public string ReferenceCode { get; set; }

    /// <summary>
    /// Gets or Sets ParentClassCode
    /// </summary>
    [DataMember(Name="parentClassCode", EmitDefaultValue=false)]
    public string ParentClassCode { get; set; }

    /// <summary>
    /// Description of the class, max 101 characters long
    /// </summary>
    /// <value>Description of the class, max 101 characters long</value>
    [DataMember(Name="descriptionPart", EmitDefaultValue=false)]
    public string DescriptionPart { get; set; }

    /// <summary>
    /// Gets or Sets Children
    /// </summary>
    [DataMember(Name="children", EmitDefaultValue=false)]
    public List<ClassListItemContractV1Classes> Children { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class ClassListItemContractV1Classes {\n");
        sb.Append("  Uri: ").Append(Uri).Append("\n");
        sb.Append("  Code: ").Append(Code).Append("\n");
        sb.Append("  Name: ").Append(Name).Append("\n");
        sb.Append("  ClassType: ").Append(ClassType).Append("\n");
        sb.Append("  ReferenceCode: ").Append(ReferenceCode).Append("\n");
        sb.Append("  ParentClassCode: ").Append(ParentClassCode).Append("\n");
        sb.Append("  DescriptionPart: ").Append(DescriptionPart).Append("\n");
        sb.Append("  Children: ").Append(Children).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return this.Equals(input as ClassListItemContractV1Classes);
    }

    /// <summary>
    /// Returns true if ClassListItemContractV1Classes instances are equal
    /// </summary>
    /// <param name="input">Instance of ClassListItemContractV1Classes to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(ClassListItemContractV1Classes input)
    {
        if (input == null)
            return false;

        return 
            (
                this.Uri == input.Uri ||
                (this.Uri != null &&
                 this.Uri.Equals(input.Uri))
            ) && 
            (
                this.Code == input.Code ||
                (this.Code != null &&
                 this.Code.Equals(input.Code))
            ) && 
            (
                this.Name == input.Name ||
                (this.Name != null &&
                 this.Name.Equals(input.Name))
            ) && 
            (
                this.ClassType == input.ClassType ||
                (this.ClassType != null &&
                 this.ClassType.Equals(input.ClassType))
            ) && 
            (
                this.ReferenceCode == input.ReferenceCode ||
                (this.ReferenceCode != null &&
                 this.ReferenceCode.Equals(input.ReferenceCode))
            ) && 
            (
                this.ParentClassCode == input.ParentClassCode ||
                (this.ParentClassCode != null &&
                 this.ParentClassCode.Equals(input.ParentClassCode))
            ) && 
            (
                this.DescriptionPart == input.DescriptionPart ||
                (this.DescriptionPart != null &&
                 this.DescriptionPart.Equals(input.DescriptionPart))
            ) && 
            (
                this.Children == input.Children ||
                this.Children != null &&
                input.Children != null &&
                this.Children.SequenceEqual(input.Children)
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (this.Uri != null)
                hashCode = hashCode * 59 + this.Uri.GetHashCode();
            if (this.Code != null)
                hashCode = hashCode * 59 + this.Code.GetHashCode();
            if (this.Name != null)
                hashCode = hashCode * 59 + this.Name.GetHashCode();
            if (this.ClassType != null)
                hashCode = hashCode * 59 + this.ClassType.GetHashCode();
            if (this.ReferenceCode != null)
                hashCode = hashCode * 59 + this.ReferenceCode.GetHashCode();
            if (this.ParentClassCode != null)
                hashCode = hashCode * 59 + this.ParentClassCode.GetHashCode();
            if (this.DescriptionPart != null)
                hashCode = hashCode * 59 + this.DescriptionPart.GetHashCode();
            if (this.Children != null)
                hashCode = hashCode * 59 + this.Children.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}