/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ConsoleDemo.Model;

/// <summary>
/// ClassRelationContractV1
/// </summary>
[DataContract]
public partial class ClassRelationContractV1 :  IEquatable<ClassRelationContractV1>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ClassRelationContractV1" /> class.
    /// </summary>
    /// <param name="uri">uri.</param>
    /// <param name="relationType">Can be one of: HasReference, IsEqualTo, IsSynonymOf, IsParentOf, IsChildOf, HasPart (required).</param>
    /// <param name="relatedClassUri">Namespace URI of the related class (required).</param>
    /// <param name="relatedClassName">Name of the related class.</param>
    /// <param name="fraction">Optional provision of a fraction of the total amount (e.g. volume or weight) that applies to the class relations of one relation type.</param>
    public ClassRelationContractV1(string uri = default(string), string relationType = default(string), string relatedClassUri = default(string), string relatedClassName = default(string), double? fraction = default(double?))
    {
        // to ensure "relationType" is required (not null)
        if (relationType == null)
        {
            throw new InvalidDataException("relationType is a required property for ClassRelationContractV1 and cannot be null");
        }
        else
        {
            this.RelationType = relationType;
        }
        // to ensure "relatedClassUri" is required (not null)
        if (relatedClassUri == null)
        {
            throw new InvalidDataException("relatedClassUri is a required property for ClassRelationContractV1 and cannot be null");
        }
        else
        {
            this.RelatedClassUri = relatedClassUri;
        }
        this.Uri = uri;
        this.RelatedClassName = relatedClassName;
        this.Fraction = fraction;
    }
        
    /// <summary>
    /// Gets or Sets Uri
    /// </summary>
    [DataMember(Name="uri", EmitDefaultValue=false)]
    public string Uri { get; set; }

    /// <summary>
    /// Can be one of: HasReference, IsEqualTo, IsSynonymOf, IsParentOf, IsChildOf, HasPart
    /// </summary>
    /// <value>Can be one of: HasReference, IsEqualTo, IsSynonymOf, IsParentOf, IsChildOf, HasPart</value>
    [DataMember(Name="relationType", EmitDefaultValue=false)]
    public string RelationType { get; set; }

    /// <summary>
    /// Namespace URI of the related class
    /// </summary>
    /// <value>Namespace URI of the related class</value>
    [DataMember(Name="relatedClassUri", EmitDefaultValue=false)]
    public string RelatedClassUri { get; set; }

    /// <summary>
    /// Name of the related class
    /// </summary>
    /// <value>Name of the related class</value>
    [DataMember(Name="relatedClassName", EmitDefaultValue=false)]
    public string RelatedClassName { get; set; }

    /// <summary>
    /// Optional provision of a fraction of the total amount (e.g. volume or weight) that applies to the class relations of one relation type
    /// </summary>
    /// <value>Optional provision of a fraction of the total amount (e.g. volume or weight) that applies to the class relations of one relation type</value>
    [DataMember(Name="fraction", EmitDefaultValue=false)]
    public double? Fraction { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class ClassRelationContractV1 {\n");
        sb.Append("  Uri: ").Append(Uri).Append("\n");
        sb.Append("  RelationType: ").Append(RelationType).Append("\n");
        sb.Append("  RelatedClassUri: ").Append(RelatedClassUri).Append("\n");
        sb.Append("  RelatedClassName: ").Append(RelatedClassName).Append("\n");
        sb.Append("  Fraction: ").Append(Fraction).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }
  
    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return this.Equals(input as ClassRelationContractV1);
    }

    /// <summary>
    /// Returns true if ClassRelationContractV1 instances are equal
    /// </summary>
    /// <param name="input">Instance of ClassRelationContractV1 to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(ClassRelationContractV1 input)
    {
        if (input == null)
            return false;

        return 
            (
                this.Uri == input.Uri ||
                (this.Uri != null &&
                 this.Uri.Equals(input.Uri))
            ) && 
            (
                this.RelationType == input.RelationType ||
                (this.RelationType != null &&
                 this.RelationType.Equals(input.RelationType))
            ) && 
            (
                this.RelatedClassUri == input.RelatedClassUri ||
                (this.RelatedClassUri != null &&
                 this.RelatedClassUri.Equals(input.RelatedClassUri))
            ) && 
            (
                this.RelatedClassName == input.RelatedClassName ||
                (this.RelatedClassName != null &&
                 this.RelatedClassName.Equals(input.RelatedClassName))
            ) && 
            (
                this.Fraction == input.Fraction ||
                (this.Fraction != null &&
                 this.Fraction.Equals(input.Fraction))
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (this.Uri != null)
                hashCode = hashCode * 59 + this.Uri.GetHashCode();
            if (this.RelationType != null)
                hashCode = hashCode * 59 + this.RelationType.GetHashCode();
            if (this.RelatedClassUri != null)
                hashCode = hashCode * 59 + this.RelatedClassUri.GetHashCode();
            if (this.RelatedClassName != null)
                hashCode = hashCode * 59 + this.RelatedClassName.GetHashCode();
            if (this.Fraction != null)
                hashCode = hashCode * 59 + this.Fraction.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}