/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ConsoleDemo.Model;

/// <summary>
/// ClassSearchResponseClassContractV1
/// </summary>
[DataContract]
public partial class ClassSearchResponseClassContractV1 :  IEquatable<ClassSearchResponseClassContractV1>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ClassSearchResponseClassContractV1" /> class.
    /// </summary>
    /// <param name="dictionaryUri">Unique identification of the dictionary the class belongs to.</param>
    /// <param name="dictionaryName">Name of the dictionary the class belongs to.</param>
    /// <param name="name">Name of the class.</param>
    /// <param name="referenceCode">Code that can be used for dictionary specific purposes.</param>
    /// <param name="uri">Unique identification of the class.</param>
    /// <param name="classType">Type of the class.</param>
    /// <param name="description">description.</param>
    /// <param name="parentClassName">parentClassName.</param>
    /// <param name="relatedIfcEntityNames">relatedIfcEntityNames.</param>
    public ClassSearchResponseClassContractV1(string dictionaryUri = default(string), string dictionaryName = default(string), string name = default(string), string referenceCode = default(string), string uri = default(string), string classType = default(string), string description = default(string), string parentClassName = default(string), List<string> relatedIfcEntityNames = default(List<string>))
    {
        this.DictionaryUri = dictionaryUri;
        this.DictionaryName = dictionaryName;
        this.Name = name;
        this.ReferenceCode = referenceCode;
        this.Uri = uri;
        this.ClassType = classType;
        this.Description = description;
        this.ParentClassName = parentClassName;
        this.RelatedIfcEntityNames = relatedIfcEntityNames;
    }
        
    /// <summary>
    /// Unique identification of the dictionary the class belongs to
    /// </summary>
    /// <value>Unique identification of the dictionary the class belongs to</value>
    [DataMember(Name="dictionaryUri", EmitDefaultValue=false)]
    public string DictionaryUri { get; set; }

    /// <summary>
    /// Name of the dictionary the class belongs to
    /// </summary>
    /// <value>Name of the dictionary the class belongs to</value>
    [DataMember(Name="dictionaryName", EmitDefaultValue=false)]
    public string DictionaryName { get; set; }

    /// <summary>
    /// Name of the class
    /// </summary>
    /// <value>Name of the class</value>
    [DataMember(Name="name", EmitDefaultValue=false)]
    public string Name { get; set; }

    /// <summary>
    /// Code that can be used for dictionary specific purposes
    /// </summary>
    /// <value>Code that can be used for dictionary specific purposes</value>
    [DataMember(Name="referenceCode", EmitDefaultValue=false)]
    public string ReferenceCode { get; set; }

    /// <summary>
    /// Unique identification of the class
    /// </summary>
    /// <value>Unique identification of the class</value>
    [DataMember(Name="uri", EmitDefaultValue=false)]
    public string Uri { get; set; }

    /// <summary>
    /// Type of the class
    /// </summary>
    /// <value>Type of the class</value>
    [DataMember(Name="classType", EmitDefaultValue=false)]
    public string ClassType { get; set; }

    /// <summary>
    /// Gets or Sets Description
    /// </summary>
    [DataMember(Name="description", EmitDefaultValue=false)]
    public string Description { get; set; }

    /// <summary>
    /// Gets or Sets ParentClassName
    /// </summary>
    [DataMember(Name="parentClassName", EmitDefaultValue=false)]
    public string ParentClassName { get; set; }

    /// <summary>
    /// Gets or Sets RelatedIfcEntityNames
    /// </summary>
    [DataMember(Name="relatedIfcEntityNames", EmitDefaultValue=false)]
    public List<string> RelatedIfcEntityNames { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class ClassSearchResponseClassContractV1 {\n");
        sb.Append("  DictionaryUri: ").Append(DictionaryUri).Append("\n");
        sb.Append("  DictionaryName: ").Append(DictionaryName).Append("\n");
        sb.Append("  Name: ").Append(Name).Append("\n");
        sb.Append("  ReferenceCode: ").Append(ReferenceCode).Append("\n");
        sb.Append("  Uri: ").Append(Uri).Append("\n");
        sb.Append("  ClassType: ").Append(ClassType).Append("\n");
        sb.Append("  Description: ").Append(Description).Append("\n");
        sb.Append("  ParentClassName: ").Append(ParentClassName).Append("\n");
        sb.Append("  RelatedIfcEntityNames: ").Append(RelatedIfcEntityNames).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return this.Equals(input as ClassSearchResponseClassContractV1);
    }

    /// <summary>
    /// Returns true if ClassSearchResponseClassContractV1 instances are equal
    /// </summary>
    /// <param name="input">Instance of ClassSearchResponseClassContractV1 to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(ClassSearchResponseClassContractV1 input)
    {
        if (input == null)
            return false;

        return 
            (
                this.DictionaryUri == input.DictionaryUri ||
                (this.DictionaryUri != null &&
                 this.DictionaryUri.Equals(input.DictionaryUri))
            ) && 
            (
                this.DictionaryName == input.DictionaryName ||
                (this.DictionaryName != null &&
                 this.DictionaryName.Equals(input.DictionaryName))
            ) && 
            (
                this.Name == input.Name ||
                (this.Name != null &&
                 this.Name.Equals(input.Name))
            ) && 
            (
                this.ReferenceCode == input.ReferenceCode ||
                (this.ReferenceCode != null &&
                 this.ReferenceCode.Equals(input.ReferenceCode))
            ) && 
            (
                this.Uri == input.Uri ||
                (this.Uri != null &&
                 this.Uri.Equals(input.Uri))
            ) && 
            (
                this.ClassType == input.ClassType ||
                (this.ClassType != null &&
                 this.ClassType.Equals(input.ClassType))
            ) && 
            (
                this.Description == input.Description ||
                (this.Description != null &&
                 this.Description.Equals(input.Description))
            ) && 
            (
                this.ParentClassName == input.ParentClassName ||
                (this.ParentClassName != null &&
                 this.ParentClassName.Equals(input.ParentClassName))
            ) && 
            (
                this.RelatedIfcEntityNames == input.RelatedIfcEntityNames ||
                this.RelatedIfcEntityNames != null &&
                input.RelatedIfcEntityNames != null &&
                this.RelatedIfcEntityNames.SequenceEqual(input.RelatedIfcEntityNames)
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (this.DictionaryUri != null)
                hashCode = hashCode * 59 + this.DictionaryUri.GetHashCode();
            if (this.DictionaryName != null)
                hashCode = hashCode * 59 + this.DictionaryName.GetHashCode();
            if (this.Name != null)
                hashCode = hashCode * 59 + this.Name.GetHashCode();
            if (this.ReferenceCode != null)
                hashCode = hashCode * 59 + this.ReferenceCode.GetHashCode();
            if (this.Uri != null)
                hashCode = hashCode * 59 + this.Uri.GetHashCode();
            if (this.ClassType != null)
                hashCode = hashCode * 59 + this.ClassType.GetHashCode();
            if (this.Description != null)
                hashCode = hashCode * 59 + this.Description.GetHashCode();
            if (this.ParentClassName != null)
                hashCode = hashCode * 59 + this.ParentClassName.GetHashCode();
            if (this.RelatedIfcEntityNames != null)
                hashCode = hashCode * 59 + this.RelatedIfcEntityNames.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}