/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ConsoleDemo.Model;

/// <summary>
/// DictionaryClassesResponseContractV1Classes
/// </summary>
[DataContract]
public partial class DictionaryClassesResponseContractV1Classes :  IEquatable<DictionaryClassesResponseContractV1Classes>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="DictionaryClassesResponseContractV1Classes" /> class.
    /// </summary>
    /// <param name="code">code (required).</param>
    /// <param name="uri">uri (required).</param>
    /// <param name="name">name (required).</param>
    /// <param name="version">version (required).</param>
    /// <param name="organizationCodeOwner">organizationCodeOwner (required).</param>
    /// <param name="organizationNameOwner">organizationNameOwner (required).</param>
    /// <param name="changeRequestEmail">changeRequestEmail.</param>
    /// <param name="defaultLanguageCode">The default language for this domain (required).</param>
    /// <param name="isLatestVersion">isLatestVersion (required).</param>
    /// <param name="isVerified">isVerified (required).</param>
    /// <param name="license">Name or short description of the license under which you can use this data.</param>
    /// <param name="licenseUrl">URL where you can find more details about the license or default link to info about licensing.</param>
    /// <param name="qualityAssuranceProcedure">Name or short description of the quality assurance procedure used while creating and maintaining the domain data.</param>
    /// <param name="qualityAssuranceProcedureUrl">URL where you can find more details about the quality assurance procedure.</param>
    /// <param name="status">For state indication, like \&quot;Preview\&quot;, \&quot;Active\&quot;, \&quot;InActive\&quot;, \&quot;Released.</param>
    /// <param name="moreInfoUrl">Url to site with more info on domain.</param>
    /// <param name="releaseDate">Date of the release of this version.</param>
    /// <param name="lastUpdatedUtc">Date and time the data of the domain has been last updated in bSDD.</param>
    /// <param name="classes">classes.</param>
    /// <param name="classesTotalCount">Total number of classes within the dictionary..</param>
    /// <param name="classesOffset">classesOffset.</param>
    /// <param name="classesCount">The returned number of classes..</param>
    public DictionaryClassesResponseContractV1Classes(string code = default(string), string uri = default(string), string name = default(string), string version = default(string), string organizationCodeOwner = default(string), string organizationNameOwner = default(string), string changeRequestEmail = default(string), string defaultLanguageCode = default(string), bool? isLatestVersion = default(bool?), bool? isVerified = default(bool?), string license = default(string), string licenseUrl = default(string), string qualityAssuranceProcedure = default(string), string qualityAssuranceProcedureUrl = default(string), string status = default(string), string moreInfoUrl = default(string), DateTime? releaseDate = default(DateTime?), DateTime? lastUpdatedUtc = default(DateTime?), List<ClassListItemContractV1Classes> classes = default(List<ClassListItemContractV1Classes>), int? classesTotalCount = default(int?), int? classesOffset = default(int?), int? classesCount = default(int?))
    {
        // to ensure "code" is required (not null)
        if (string.IsNullOrWhiteSpace(code))
        {
            throw new InvalidDataException("code is a required property for DictionaryClassesResponseContractV1Classes and cannot be null");
        }
        else
        {
            this.Code = code;
        }
        // to ensure "uri" is required (not null)
        if (uri == null)
        {
            throw new InvalidDataException("uri is a required property for DictionaryClassesResponseContractV1Classes and cannot be null");
        }
        else
        {
            this.Uri = uri;
        }
        // to ensure "name" is required (not null)
        if (name == null)
        {
            throw new InvalidDataException("name is a required property for DictionaryClassesResponseContractV1Classes and cannot be null");
        }
        else
        {
            this.Name = name;
        }
        // to ensure "version" is required (not null)
        if (string.IsNullOrWhiteSpace(version))
        {
            throw new InvalidDataException("version is a required property for DictionaryClassesResponseContractV1Classes and cannot be null");
        }
        else
        {
            this.Version = version;
        }
        // to ensure "organizationCodeOwner" is required (not null)
        if (organizationCodeOwner == null)
        {
            throw new InvalidDataException("organizationCodeOwner is a required property for DictionaryClassesResponseContractV1Classes and cannot be null");
        }
        else
        {
            this.OrganizationCodeOwner = organizationCodeOwner;
        }
        // to ensure "organizationNameOwner" is required (not null)
        if (organizationNameOwner == null)
        {
            throw new InvalidDataException("organizationNameOwner is a required property for DictionaryClassesResponseContractV1Classes and cannot be null");
        }
        else
        {
            this.OrganizationNameOwner = organizationNameOwner;
        }
        // to ensure "defaultLanguageCode" is required (not null)
        if (defaultLanguageCode == null)
        {
            throw new InvalidDataException("defaultLanguageCode is a required property for DictionaryClassesResponseContractV1Classes and cannot be null");
        }
        else
        {
            this.DefaultLanguageCode = defaultLanguageCode;
        }
        // to ensure "isLatestVersion" is required (not null)
        if (isLatestVersion == null)
        {
            throw new InvalidDataException("isLatestVersion is a required property for DictionaryClassesResponseContractV1Classes and cannot be null");
        }
        else
        {
            this.IsLatestVersion = isLatestVersion;
        }
        // to ensure "isVerified" is required (not null)
        if (isVerified == null)
        {
            throw new InvalidDataException("isVerified is a required property for DictionaryClassesResponseContractV1Classes and cannot be null");
        }
        else
        {
            this.IsVerified = isVerified;
        }
        this.ChangeRequestEmail = changeRequestEmail;
        this.License = license;
        this.LicenseUrl = licenseUrl;
        this.QualityAssuranceProcedure = qualityAssuranceProcedure;
        this.QualityAssuranceProcedureUrl = qualityAssuranceProcedureUrl;
        this.Status = status;
        this.MoreInfoUrl = moreInfoUrl;
        this.ReleaseDate = releaseDate;
        this.LastUpdatedUtc = lastUpdatedUtc;
        this.Classes = classes;
        this.ClassesTotalCount = classesTotalCount;
        this.ClassesOffset = classesOffset;
        this.ClassesCount = classesCount;
    }
        
    /// <summary>
    /// Gets or Sets Code
    /// </summary>
    [DataMember(Name="code", EmitDefaultValue=false)]
    public string Code { get; set; }

    /// <summary>
    /// Gets or Sets Uri
    /// </summary>
    [DataMember(Name="uri", EmitDefaultValue=false)]
    public string Uri { get; set; }

    /// <summary>
    /// Gets or Sets Name
    /// </summary>
    [DataMember(Name="name", EmitDefaultValue=false)]
    public string Name { get; set; }

    /// <summary>
    /// Gets or Sets Version
    /// </summary>
    [DataMember(Name="version", EmitDefaultValue=false)]
    public string Version { get; set; }

    /// <summary>
    /// Gets or Sets OrganizationCodeOwner
    /// </summary>
    [DataMember(Name="organizationCodeOwner", EmitDefaultValue=false)]
    public string OrganizationCodeOwner { get; set; }

    /// <summary>
    /// Gets or Sets OrganizationNameOwner
    /// </summary>
    [DataMember(Name="organizationNameOwner", EmitDefaultValue=false)]
    public string OrganizationNameOwner { get; set; }

    /// <summary>
    /// Gets or Sets ChangeRequestEmail
    /// </summary>
    [DataMember(Name="changeRequestEmail", EmitDefaultValue=false)]
    public string ChangeRequestEmail { get; set; }

    /// <summary>
    /// The default language for this domain
    /// </summary>
    /// <value>The default language for this domain</value>
    [DataMember(Name="defaultLanguageCode", EmitDefaultValue=false)]
    public string DefaultLanguageCode { get; set; }

    /// <summary>
    /// Gets or Sets IsLatestVersion
    /// </summary>
    [DataMember(Name="isLatestVersion", EmitDefaultValue=false)]
    public bool? IsLatestVersion { get; set; }

    /// <summary>
    /// Gets or Sets IsVerified
    /// </summary>
    [DataMember(Name="isVerified", EmitDefaultValue=false)]
    public bool? IsVerified { get; set; }

    /// <summary>
    /// Name or short description of the license under which you can use this data
    /// </summary>
    /// <value>Name or short description of the license under which you can use this data</value>
    [DataMember(Name="license", EmitDefaultValue=false)]
    public string License { get; set; }

    /// <summary>
    /// URL where you can find more details about the license or default link to info about licensing
    /// </summary>
    /// <value>URL where you can find more details about the license or default link to info about licensing</value>
    [DataMember(Name="licenseUrl", EmitDefaultValue=false)]
    public string LicenseUrl { get; set; }

    /// <summary>
    /// Name or short description of the quality assurance procedure used while creating and maintaining the domain data
    /// </summary>
    /// <value>Name or short description of the quality assurance procedure used while creating and maintaining the domain data</value>
    [DataMember(Name="qualityAssuranceProcedure", EmitDefaultValue=false)]
    public string QualityAssuranceProcedure { get; set; }

    /// <summary>
    /// URL where you can find more details about the quality assurance procedure
    /// </summary>
    /// <value>URL where you can find more details about the quality assurance procedure</value>
    [DataMember(Name="qualityAssuranceProcedureUrl", EmitDefaultValue=false)]
    public string QualityAssuranceProcedureUrl { get; set; }

    /// <summary>
    /// For state indication, like \&quot;Preview\&quot;, \&quot;Active\&quot;, \&quot;InActive\&quot;, \&quot;Released
    /// </summary>
    /// <value>For state indication, like \&quot;Preview\&quot;, \&quot;Active\&quot;, \&quot;InActive\&quot;, \&quot;Released</value>
    [DataMember(Name="status", EmitDefaultValue=false)]
    public string Status { get; set; }

    /// <summary>
    /// Url to site with more info on domain
    /// </summary>
    /// <value>Url to site with more info on domain</value>
    [DataMember(Name="moreInfoUrl", EmitDefaultValue=false)]
    public string MoreInfoUrl { get; set; }

    /// <summary>
    /// Date of the release of this version
    /// </summary>
    /// <value>Date of the release of this version</value>
    [DataMember(Name="releaseDate", EmitDefaultValue=false)]
    public DateTime? ReleaseDate { get; set; }

    /// <summary>
    /// Date and time the data of the domain has been last updated in bSDD
    /// </summary>
    /// <value>Date and time the data of the domain has been last updated in bSDD</value>
    [DataMember(Name="lastUpdatedUtc", EmitDefaultValue=false)]
    public DateTime? LastUpdatedUtc { get; set; }

    /// <summary>
    /// Gets or Sets Classes
    /// </summary>
    [DataMember(Name="classes", EmitDefaultValue=false)]
    public List<ClassListItemContractV1Classes> Classes { get; set; }

    /// <summary>
    /// Total number of classes within the dictionary.
    /// </summary>
    /// <value>Total number of classes within the dictionary.</value>
    [DataMember(Name="classesTotalCount", EmitDefaultValue=false)]
    public int? ClassesTotalCount { get; set; }

    /// <summary>
    /// Gets or Sets ClassesOffset
    /// </summary>
    [DataMember(Name="classesOffset", EmitDefaultValue=false)]
    public int? ClassesOffset { get; set; }

    /// <summary>
    /// The returned number of classes.
    /// </summary>
    /// <value>The returned number of classes.</value>
    [DataMember(Name="classesCount", EmitDefaultValue=false)]
    public int? ClassesCount { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class DictionaryClassesResponseContractV1Classes {\n");
        sb.Append("  Code: ").Append(Code).Append("\n");
        sb.Append("  Uri: ").Append(Uri).Append("\n");
        sb.Append("  Name: ").Append(Name).Append("\n");
        sb.Append("  Version: ").Append(Version).Append("\n");
        sb.Append("  OrganizationCodeOwner: ").Append(OrganizationCodeOwner).Append("\n");
        sb.Append("  OrganizationNameOwner: ").Append(OrganizationNameOwner).Append("\n");
        sb.Append("  ChangeRequestEmail: ").Append(ChangeRequestEmail).Append("\n");
        sb.Append("  DefaultLanguageCode: ").Append(DefaultLanguageCode).Append("\n");
        sb.Append("  IsLatestVersion: ").Append(IsLatestVersion).Append("\n");
        sb.Append("  IsVerified: ").Append(IsVerified).Append("\n");
        sb.Append("  License: ").Append(License).Append("\n");
        sb.Append("  LicenseUrl: ").Append(LicenseUrl).Append("\n");
        sb.Append("  QualityAssuranceProcedure: ").Append(QualityAssuranceProcedure).Append("\n");
        sb.Append("  QualityAssuranceProcedureUrl: ").Append(QualityAssuranceProcedureUrl).Append("\n");
        sb.Append("  Status: ").Append(Status).Append("\n");
        sb.Append("  MoreInfoUrl: ").Append(MoreInfoUrl).Append("\n");
        sb.Append("  ReleaseDate: ").Append(ReleaseDate).Append("\n");
        sb.Append("  LastUpdatedUtc: ").Append(LastUpdatedUtc).Append("\n");
        sb.Append("  Classes: ").Append(Classes).Append("\n");
        sb.Append("  ClassesTotalCount: ").Append(ClassesTotalCount).Append("\n");
        sb.Append("  ClassesOffset: ").Append(ClassesOffset).Append("\n");
        sb.Append("  ClassesCount: ").Append(ClassesCount).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }
  
    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return this.Equals(input as DictionaryClassesResponseContractV1Classes);
    }

    /// <summary>
    /// Returns true if DictionaryClassesResponseContractV1Classes instances are equal
    /// </summary>
    /// <param name="input">Instance of DictionaryClassesResponseContractV1Classes to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(DictionaryClassesResponseContractV1Classes input)
    {
        if (input == null)
            return false;

        return 
            (
                this.Code == input.Code ||
                (this.Code != null &&
                 this.Code.Equals(input.Code))
            ) && 
            (
                this.Uri == input.Uri ||
                (this.Uri != null &&
                 this.Uri.Equals(input.Uri))
            ) && 
            (
                this.Name == input.Name ||
                (this.Name != null &&
                 this.Name.Equals(input.Name))
            ) && 
            (
                this.Version == input.Version ||
                (this.Version != null &&
                 this.Version.Equals(input.Version))
            ) && 
            (
                this.OrganizationCodeOwner == input.OrganizationCodeOwner ||
                (this.OrganizationCodeOwner != null &&
                 this.OrganizationCodeOwner.Equals(input.OrganizationCodeOwner))
            ) && 
            (
                this.OrganizationNameOwner == input.OrganizationNameOwner ||
                (this.OrganizationNameOwner != null &&
                 this.OrganizationNameOwner.Equals(input.OrganizationNameOwner))
            ) && 
            (
                this.ChangeRequestEmail == input.ChangeRequestEmail ||
                (this.ChangeRequestEmail != null &&
                 this.ChangeRequestEmail.Equals(input.ChangeRequestEmail))
            ) && 
            (
                this.DefaultLanguageCode == input.DefaultLanguageCode ||
                (this.DefaultLanguageCode != null &&
                 this.DefaultLanguageCode.Equals(input.DefaultLanguageCode))
            ) && 
            (
                this.IsLatestVersion == input.IsLatestVersion ||
                (this.IsLatestVersion != null &&
                 this.IsLatestVersion.Equals(input.IsLatestVersion))
            ) && 
            (
                this.IsVerified == input.IsVerified ||
                (this.IsVerified != null &&
                 this.IsVerified.Equals(input.IsVerified))
            ) && 
            (
                this.License == input.License ||
                (this.License != null &&
                 this.License.Equals(input.License))
            ) && 
            (
                this.LicenseUrl == input.LicenseUrl ||
                (this.LicenseUrl != null &&
                 this.LicenseUrl.Equals(input.LicenseUrl))
            ) && 
            (
                this.QualityAssuranceProcedure == input.QualityAssuranceProcedure ||
                (this.QualityAssuranceProcedure != null &&
                 this.QualityAssuranceProcedure.Equals(input.QualityAssuranceProcedure))
            ) && 
            (
                this.QualityAssuranceProcedureUrl == input.QualityAssuranceProcedureUrl ||
                (this.QualityAssuranceProcedureUrl != null &&
                 this.QualityAssuranceProcedureUrl.Equals(input.QualityAssuranceProcedureUrl))
            ) && 
            (
                this.Status == input.Status ||
                (this.Status != null &&
                 this.Status.Equals(input.Status))
            ) && 
            (
                this.MoreInfoUrl == input.MoreInfoUrl ||
                (this.MoreInfoUrl != null &&
                 this.MoreInfoUrl.Equals(input.MoreInfoUrl))
            ) && 
            (
                this.ReleaseDate == input.ReleaseDate ||
                (this.ReleaseDate != null &&
                 this.ReleaseDate.Equals(input.ReleaseDate))
            ) && 
            (
                this.LastUpdatedUtc == input.LastUpdatedUtc ||
                (this.LastUpdatedUtc != null &&
                 this.LastUpdatedUtc.Equals(input.LastUpdatedUtc))
            ) && 
            (
                this.Classes == input.Classes ||
                this.Classes != null &&
                input.Classes != null &&
                this.Classes.SequenceEqual(input.Classes)
            ) && 
            (
                this.ClassesTotalCount == input.ClassesTotalCount ||
                (this.ClassesTotalCount != null &&
                 this.ClassesTotalCount.Equals(input.ClassesTotalCount))
            ) && 
            (
                this.ClassesOffset == input.ClassesOffset ||
                (this.ClassesOffset != null &&
                 this.ClassesOffset.Equals(input.ClassesOffset))
            ) && 
            (
                this.ClassesCount == input.ClassesCount ||
                (this.ClassesCount != null &&
                 this.ClassesCount.Equals(input.ClassesCount))
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (this.Code != null)
                hashCode = hashCode * 59 + this.Code.GetHashCode();
            if (this.Uri != null)
                hashCode = hashCode * 59 + this.Uri.GetHashCode();
            if (this.Name != null)
                hashCode = hashCode * 59 + this.Name.GetHashCode();
            if (this.Version != null)
                hashCode = hashCode * 59 + this.Version.GetHashCode();
            if (this.OrganizationCodeOwner != null)
                hashCode = hashCode * 59 + this.OrganizationCodeOwner.GetHashCode();
            if (this.OrganizationNameOwner != null)
                hashCode = hashCode * 59 + this.OrganizationNameOwner.GetHashCode();
            if (this.ChangeRequestEmail != null)
                hashCode = hashCode * 59 + this.ChangeRequestEmail.GetHashCode();
            if (this.DefaultLanguageCode != null)
                hashCode = hashCode * 59 + this.DefaultLanguageCode.GetHashCode();
            if (this.IsLatestVersion != null)
                hashCode = hashCode * 59 + this.IsLatestVersion.GetHashCode();
            if (this.IsVerified != null)
                hashCode = hashCode * 59 + this.IsVerified.GetHashCode();
            if (this.License != null)
                hashCode = hashCode * 59 + this.License.GetHashCode();
            if (this.LicenseUrl != null)
                hashCode = hashCode * 59 + this.LicenseUrl.GetHashCode();
            if (this.QualityAssuranceProcedure != null)
                hashCode = hashCode * 59 + this.QualityAssuranceProcedure.GetHashCode();
            if (this.QualityAssuranceProcedureUrl != null)
                hashCode = hashCode * 59 + this.QualityAssuranceProcedureUrl.GetHashCode();
            if (this.Status != null)
                hashCode = hashCode * 59 + this.Status.GetHashCode();
            if (this.MoreInfoUrl != null)
                hashCode = hashCode * 59 + this.MoreInfoUrl.GetHashCode();
            if (this.ReleaseDate != null)
                hashCode = hashCode * 59 + this.ReleaseDate.GetHashCode();
            if (this.LastUpdatedUtc != null)
                hashCode = hashCode * 59 + this.LastUpdatedUtc.GetHashCode();
            if (this.Classes != null)
                hashCode = hashCode * 59 + this.Classes.GetHashCode();
            if (this.ClassesTotalCount != null)
                hashCode = hashCode * 59 + this.ClassesTotalCount.GetHashCode();
            if (this.ClassesOffset != null)
                hashCode = hashCode * 59 + this.ClassesOffset.GetHashCode();
            if (this.ClassesCount != null)
                hashCode = hashCode * 59 + this.ClassesCount.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}