/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ConsoleDemo.Model;

/// <summary>
/// HierarchyItemContractV1
/// </summary>
[DataContract]
public partial class HierarchyItemContractV1 :  IEquatable<HierarchyItemContractV1>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="HierarchyItemContractV1" /> class.
    /// </summary>
    /// <param name="level">level (required).</param>
    /// <param name="name">name (required).</param>
    /// <param name="code">code (required).</param>
    /// <param name="uri">uri (required).</param>
    public HierarchyItemContractV1(int? level = default(int?), string name = default(string), string code = default(string), string uri = default(string))
    {
        // to ensure "level" is required (not null)
        if (level == null)
        {
            throw new InvalidDataException("level is a required property for HierarchyItemContractV1 and cannot be null");
        }
        else
        {
            this.Level = level;
        }
        // to ensure "name" is required (not null)
        if (name == null)
        {
            throw new InvalidDataException("name is a required property for HierarchyItemContractV1 and cannot be null");
        }
        else
        {
            this.Name = name;
        }
        // to ensure "code" is required (not null)
        if (string.IsNullOrWhiteSpace(code))
        {
            throw new InvalidDataException("code is a required property for HierarchyItemContractV1 and cannot be null");
        }
        else
        {
            this.Code = code;
        }
        // to ensure "uri" is required (not null)
        if (string.IsNullOrWhiteSpace(uri))
        {
            throw new InvalidDataException("uri is a required property for HierarchyItemContractV1 and cannot be null");
        }
        else
        {
            this.Uri = uri;
        }
    }
        
    /// <summary>
    /// Gets or Sets Level
    /// </summary>
    [DataMember(Name="level", EmitDefaultValue=false)]
    public int? Level { get; set; }

    /// <summary>
    /// Gets or Sets Name
    /// </summary>
    [DataMember(Name="name", EmitDefaultValue=false)]
    public string Name { get; set; }

    /// <summary>
    /// Gets or Sets Code
    /// </summary>
    [DataMember(Name="code", EmitDefaultValue=false)]
    public string Code { get; set; }

    /// <summary>
    /// Gets or Sets Uri
    /// </summary>
    [DataMember(Name="uri", EmitDefaultValue=false)]
    public string Uri { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class HierarchyItemContractV1 {\n");
        sb.Append("  Level: ").Append(Level).Append("\n");
        sb.Append("  Name: ").Append(Name).Append("\n");
        sb.Append("  Code: ").Append(Code).Append("\n");
        sb.Append("  Uri: ").Append(Uri).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return this.Equals(input as HierarchyItemContractV1);
    }

    /// <summary>
    /// Returns true if HierarchyItemContractV1 instances are equal
    /// </summary>
    /// <param name="input">Instance of HierarchyItemContractV1 to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(HierarchyItemContractV1 input)
    {
        if (input == null)
            return false;

        return 
            (
                this.Level == input.Level ||
                (this.Level != null &&
                 this.Level.Equals(input.Level))
            ) && 
            (
                this.Name == input.Name ||
                (this.Name != null &&
                 this.Name.Equals(input.Name))
            ) && 
            (
                this.Code == input.Code ||
                (this.Code != null &&
                 this.Code.Equals(input.Code))
            ) && 
            (
                this.Uri == input.Uri ||
                (this.Uri != null &&
                 this.Uri.Equals(input.Uri))
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (this.Level != null)
                hashCode = hashCode * 59 + this.Level.GetHashCode();
            if (this.Name != null)
                hashCode = hashCode * 59 + this.Name.GetHashCode();
            if (this.Code != null)
                hashCode = hashCode * 59 + this.Code.GetHashCode();
            if (this.Uri != null)
                hashCode = hashCode * 59 + this.Uri.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}