/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;

namespace ConsoleDemo.Model;

/// <summary>
/// Defines InternalExternalOption.v1
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum InternalExternalOptionV1
{
    /// <summary>
    /// Enum NUMBER_0 for value: 0
    /// </summary>
    [EnumMember(Value = "0")]
    NUMBER_0 = 1,
    /// <summary>
    /// Enum NUMBER_1 for value: 1
    /// </summary>
    [EnumMember(Value = "1")]
    NUMBER_1 = 2,
    /// <summary>
    /// Enum NUMBER_2 for value: 2
    /// </summary>
    [EnumMember(Value = "2")]
    NUMBER_2 = 3    }