/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ConsoleDemo.Model;

/// <summary>
/// PopularDictionariesResponseContractV1
/// </summary>
[DataContract]
public partial class PopularDictionariesResponseContractV1 :  IEquatable<PopularDictionariesResponseContractV1>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="PopularDictionariesResponseContractV1" /> class.
    /// </summary>
    /// <param name="popularDictionaries">popularDictionaries.</param>
    public PopularDictionariesResponseContractV1(List<PopularDictionaryContractV1> popularDictionaries = default(List<PopularDictionaryContractV1>))
    {
        this.PopularDictionaries = popularDictionaries;
    }
        
    /// <summary>
    /// Gets or Sets PopularDictionaries
    /// </summary>
    [DataMember(Name="popularDictionaries", EmitDefaultValue=false)]
    public List<PopularDictionaryContractV1> PopularDictionaries { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class PopularDictionariesResponseContractV1 {\n");
        sb.Append("  PopularDictionaries: ").Append(PopularDictionaries).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return this.Equals(input as PopularDictionariesResponseContractV1);
    }

    /// <summary>
    /// Returns true if PopularDictionariesResponseContractV1 instances are equal
    /// </summary>
    /// <param name="input">Instance of PopularDictionariesResponseContractV1 to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(PopularDictionariesResponseContractV1 input)
    {
        if (input == null)
            return false;

        return 
        (
            this.PopularDictionaries == input.PopularDictionaries ||
            this.PopularDictionaries != null &&
            input.PopularDictionaries != null &&
            this.PopularDictionaries.SequenceEqual(input.PopularDictionaries)
        );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (this.PopularDictionaries != null)
                hashCode = hashCode * 59 + this.PopularDictionaries.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}