/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ConsoleDemo.Model;

/// <summary>
/// PropertyRelationContractV4
/// </summary>
[DataContract]
public partial class PropertyRelationContractV4 :  IEquatable<PropertyRelationContractV4>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="PropertyRelationContractV4" /> class.
    /// </summary>
    /// <param name="uri">Globally unique identification of the relation.</param>
    /// <param name="relationType">The relation with the other property: e.g. HasReference, IsEqualTo.</param>
    /// <param name="relatedPropertyUri">Namespace URI of the related property.</param>
    /// <param name="relatedPropertyName">Name of the related property.</param>
    public PropertyRelationContractV4(string uri = default(string), string relationType = default(string), string relatedPropertyUri = default(string), string relatedPropertyName = default(string))
    {
        this.Uri = uri;
        this.RelationType = relationType;
        this.RelatedPropertyUri = relatedPropertyUri;
        this.RelatedPropertyName = relatedPropertyName;
    }
        
    /// <summary>
    /// Globally unique identification of the relation
    /// </summary>
    /// <value>Globally unique identification of the relation</value>
    [DataMember(Name="uri", EmitDefaultValue=false)]
    public string Uri { get; set; }

    /// <summary>
    /// The relation with the other property: e.g. HasReference, IsEqualTo
    /// </summary>
    /// <value>The relation with the other property: e.g. HasReference, IsEqualTo</value>
    [DataMember(Name="relationType", EmitDefaultValue=false)]
    public string RelationType { get; set; }

    /// <summary>
    /// Namespace URI of the related property
    /// </summary>
    /// <value>Namespace URI of the related property</value>
    [DataMember(Name="relatedPropertyUri", EmitDefaultValue=false)]
    public string RelatedPropertyUri { get; set; }

    /// <summary>
    /// Name of the related property
    /// </summary>
    /// <value>Name of the related property</value>
    [DataMember(Name="relatedPropertyName", EmitDefaultValue=false)]
    public string RelatedPropertyName { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class PropertyRelationContractV4 {\n");
        sb.Append("  Uri: ").Append(Uri).Append("\n");
        sb.Append("  RelationType: ").Append(RelationType).Append("\n");
        sb.Append("  RelatedPropertyUri: ").Append(RelatedPropertyUri).Append("\n");
        sb.Append("  RelatedPropertyName: ").Append(RelatedPropertyName).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return this.Equals(input as PropertyRelationContractV4);
    }

    /// <summary>
    /// Returns true if PropertyRelationContractV4 instances are equal
    /// </summary>
    /// <param name="input">Instance of PropertyRelationContractV4 to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(PropertyRelationContractV4 input)
    {
        if (input == null)
            return false;

        return 
            (
                this.Uri == input.Uri ||
                (this.Uri != null &&
                 this.Uri.Equals(input.Uri))
            ) && 
            (
                this.RelationType == input.RelationType ||
                (this.RelationType != null &&
                 this.RelationType.Equals(input.RelationType))
            ) && 
            (
                this.RelatedPropertyUri == input.RelatedPropertyUri ||
                (this.RelatedPropertyUri != null &&
                 this.RelatedPropertyUri.Equals(input.RelatedPropertyUri))
            ) && 
            (
                this.RelatedPropertyName == input.RelatedPropertyName ||
                (this.RelatedPropertyName != null &&
                 this.RelatedPropertyName.Equals(input.RelatedPropertyName))
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (this.Uri != null)
                hashCode = hashCode * 59 + this.Uri.GetHashCode();
            if (this.RelationType != null)
                hashCode = hashCode * 59 + this.RelationType.GetHashCode();
            if (this.RelatedPropertyUri != null)
                hashCode = hashCode * 59 + this.RelatedPropertyUri.GetHashCode();
            if (this.RelatedPropertyName != null)
                hashCode = hashCode * 59 + this.RelatedPropertyName.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}