/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ConsoleDemo.Model;

/// <summary>
/// PropertyClassesContractV1
/// </summary>
[DataContract]
public partial class PropertyClassesContractV1 :  IEquatable<PropertyClassesContractV1>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="PropertyClassesContractV1" /> class.
    /// </summary>
    /// <param name="totalCount">totalCount.</param>
    /// <param name="offset">offset.</param>
    /// <param name="count">count.</param>
    /// <param name="propertyUri">Uri of the property.</param>
    /// <param name="propertyClasses">List of classes having this property.</param>
    public PropertyClassesContractV1(int? totalCount = default(int?), int? offset = default(int?), int? count = default(int?), string propertyUri = default(string), List<PropertyClassItemContractV1> propertyClasses = default(List<PropertyClassItemContractV1>))
    {
        this.TotalCount = totalCount;
        this.Offset = offset;
        this.Count = count;
        this.PropertyUri = propertyUri;
        this.PropertyClasses = propertyClasses;
    }
        
    /// <summary>
    /// Gets or Sets TotalCount
    /// </summary>
    [DataMember(Name="totalCount", EmitDefaultValue=false)]
    public int? TotalCount { get; set; }

    /// <summary>
    /// Gets or Sets Offset
    /// </summary>
    [DataMember(Name="offset", EmitDefaultValue=false)]
    public int? Offset { get; set; }

    /// <summary>
    /// Gets or Sets Count
    /// </summary>
    [DataMember(Name="count", EmitDefaultValue=false)]
    public int? Count { get; set; }

    /// <summary>
    /// Uri of the property
    /// </summary>
    /// <value>Uri of the property</value>
    [DataMember(Name="propertyUri", EmitDefaultValue=false)]
    public string PropertyUri { get; set; }

    /// <summary>
    /// List of classes having this property
    /// </summary>
    /// <value>List of classes having this property</value>
    [DataMember(Name="propertyClasses", EmitDefaultValue=false)]
    public List<PropertyClassItemContractV1> PropertyClasses { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class PropertyClassesContractV1 {\n");
        sb.Append("  TotalCount: ").Append(TotalCount).Append("\n");
        sb.Append("  Offset: ").Append(Offset).Append("\n");
        sb.Append("  Count: ").Append(Count).Append("\n");
        sb.Append("  PropertyUri: ").Append(PropertyUri).Append("\n");
        sb.Append("  PropertyClasses: ").Append(PropertyClasses).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }
  
    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return this.Equals(input as PropertyClassesContractV1);
    }

    /// <summary>
    /// Returns true if PropertyClassesContractV1 instances are equal
    /// </summary>
    /// <param name="input">Instance of PropertyClassesContractV1 to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(PropertyClassesContractV1 input)
    {
        if (input == null)
            return false;

        return 
            (
                this.TotalCount == input.TotalCount ||
                (this.TotalCount != null &&
                 this.TotalCount.Equals(input.TotalCount))
            ) && 
            (
                this.Offset == input.Offset ||
                (this.Offset != null &&
                 this.Offset.Equals(input.Offset))
            ) && 
            (
                this.Count == input.Count ||
                (this.Count != null &&
                 this.Count.Equals(input.Count))
            ) && 
            (
                this.PropertyUri == input.PropertyUri ||
                (this.PropertyUri != null &&
                 this.PropertyUri.Equals(input.PropertyUri))
            ) && 
            (
                this.PropertyClasses == input.PropertyClasses ||
                this.PropertyClasses != null &&
                input.PropertyClasses != null &&
                this.PropertyClasses.SequenceEqual(input.PropertyClasses)
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (this.TotalCount != null)
                hashCode = hashCode * 59 + this.TotalCount.GetHashCode();
            if (this.Offset != null)
                hashCode = hashCode * 59 + this.Offset.GetHashCode();
            if (this.Count != null)
                hashCode = hashCode * 59 + this.Count.GetHashCode();
            if (this.PropertyUri != null)
                hashCode = hashCode * 59 + this.PropertyUri.GetHashCode();
            if (this.PropertyClasses != null)
                hashCode = hashCode * 59 + this.PropertyClasses.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}