/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ConsoleDemo.Model;

/// <summary>
/// PropertyValueContractV4
/// </summary>
[DataContract]
public partial class PropertyValueContractV4 :  IEquatable<PropertyValueContractV4>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="PropertyValueContractV4" /> class.
    /// </summary>
    /// <param name="uri">Globally unique identification of the value.</param>
    /// <param name="code">Identification of the value (unique within the property).</param>
    /// <param name="value">Allowed value of the property (required).</param>
    /// <param name="description">Description of the value.</param>
    /// <param name="sortNumber">(Optional) Sort number of value within the list of values for the Property.</param>
    public PropertyValueContractV4(string uri = default(string), string code = default(string), string value = default(string), string description = default(string), int? sortNumber = default(int?))
    {
        // to ensure "value" is required (not null)
        if (value == null)
        {
            throw new InvalidDataException("value is a required property for PropertyValueContractV4 and cannot be null");
        }
        else
        {
            this.Value = value;
        }
        this.Uri = uri;
        this.Code = code;
        this.Description = description;
        this.SortNumber = sortNumber;
    }
        
    /// <summary>
    /// Globally unique identification of the value
    /// </summary>
    /// <value>Globally unique identification of the value</value>
    [DataMember(Name="uri", EmitDefaultValue=false)]
    public string Uri { get; set; }

    /// <summary>
    /// Identification of the value (unique within the property)
    /// </summary>
    /// <value>Identification of the value (unique within the property)</value>
    [DataMember(Name="code", EmitDefaultValue=false)]
    public string Code { get; set; }

    /// <summary>
    /// Allowed value of the property
    /// </summary>
    /// <value>Allowed value of the property</value>
    [DataMember(Name="value", EmitDefaultValue=false)]
    public string Value { get; set; }

    /// <summary>
    /// Description of the value
    /// </summary>
    /// <value>Description of the value</value>
    [DataMember(Name="description", EmitDefaultValue=false)]
    public string Description { get; set; }

    /// <summary>
    /// (Optional) Sort number of value within the list of values for the Property
    /// </summary>
    /// <value>(Optional) Sort number of value within the list of values for the Property</value>
    [DataMember(Name="sortNumber", EmitDefaultValue=false)]
    public int? SortNumber { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class PropertyValueContractV4 {\n");
        sb.Append("  Uri: ").Append(Uri).Append("\n");
        sb.Append("  Code: ").Append(Code).Append("\n");
        sb.Append("  Value: ").Append(Value).Append("\n");
        sb.Append("  Description: ").Append(Description).Append("\n");
        sb.Append("  SortNumber: ").Append(SortNumber).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }
  
    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return this.Equals(input as PropertyValueContractV4);
    }

    /// <summary>
    /// Returns true if PropertyValueContractV4 instances are equal
    /// </summary>
    /// <param name="input">Instance of PropertyValueContractV4 to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(PropertyValueContractV4 input)
    {
        if (input == null)
            return false;

        return 
            (
                this.Uri == input.Uri ||
                (this.Uri != null &&
                 this.Uri.Equals(input.Uri))
            ) && 
            (
                this.Code == input.Code ||
                (this.Code != null &&
                 this.Code.Equals(input.Code))
            ) && 
            (
                this.Value == input.Value ||
                (this.Value != null &&
                 this.Value.Equals(input.Value))
            ) && 
            (
                this.Description == input.Description ||
                (this.Description != null &&
                 this.Description.Equals(input.Description))
            ) && 
            (
                this.SortNumber == input.SortNumber ||
                (this.SortNumber != null &&
                 this.SortNumber.Equals(input.SortNumber))
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (this.Uri != null)
                hashCode = hashCode * 59 + this.Uri.GetHashCode();
            if (this.Code != null)
                hashCode = hashCode * 59 + this.Code.GetHashCode();
            if (this.Value != null)
                hashCode = hashCode * 59 + this.Value.GetHashCode();
            if (this.Description != null)
                hashCode = hashCode * 59 + this.Description.GetHashCode();
            if (this.SortNumber != null)
                hashCode = hashCode * 59 + this.SortNumber.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}