/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ConsoleDemo.Model;

/// <summary>
/// PropertyRelationItemContractV1
/// </summary>
[DataContract]
public partial class PropertyRelationItemContractV1 :  IEquatable<PropertyRelationItemContractV1>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="PropertyRelationItemContractV1" /> class.
    /// </summary>
    /// <param name="relationType">Can be one of: HasReference, IsEqualTo, IsSimilarTo, IsParentOf (required).</param>
    /// <param name="propertyUri">URI of the related property (required).</param>
    /// <param name="propertyName">Name of the related property.</param>
    /// <param name="dictionaryUri">The URI of the dictionary that contains the related property. This URI can be used to retrieve the dictionary.</param>
    public PropertyRelationItemContractV1(string relationType = default(string), string propertyUri = default(string), string propertyName = default(string), string dictionaryUri = default(string))
    {
        // to ensure "relationType" is required (not null)
        if (relationType == null)
        {
            throw new InvalidDataException("relationType is a required property for PropertyRelationItemContractV1 and cannot be null");
        }
        else
        {
            this.RelationType = relationType;
        }
        // to ensure "propertyUri" is required (not null)
        if (propertyUri == null)
        {
            throw new InvalidDataException("propertyUri is a required property for PropertyRelationItemContractV1 and cannot be null");
        }
        else
        {
            this.PropertyUri = propertyUri;
        }
        this.PropertyName = propertyName;
        this.DictionaryUri = dictionaryUri;
    }
        
    /// <summary>
    /// Can be one of: HasReference, IsEqualTo, IsSimilarTo, IsParentOf
    /// </summary>
    /// <value>Can be one of: HasReference, IsEqualTo, IsSimilarTo, IsParentOf</value>
    [DataMember(Name="relationType", EmitDefaultValue=false)]
    public string RelationType { get; set; }

    /// <summary>
    /// URI of the related property
    /// </summary>
    /// <value>URI of the related property</value>
    [DataMember(Name="propertyUri", EmitDefaultValue=false)]
    public string PropertyUri { get; set; }

    /// <summary>
    /// Name of the related property
    /// </summary>
    /// <value>Name of the related property</value>
    [DataMember(Name="propertyName", EmitDefaultValue=false)]
    public string PropertyName { get; set; }

    /// <summary>
    /// The URI of the dictionary that contains the related property. This URI can be used to retrieve the dictionary
    /// </summary>
    /// <value>The URI of the dictionary that contains the related property. This URI can be used to retrieve the dictionary</value>
    [DataMember(Name="dictionaryUri", EmitDefaultValue=false)]
    public string DictionaryUri { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class PropertyRelationItemContractV1 {\n");
        sb.Append("  RelationType: ").Append(RelationType).Append("\n");
        sb.Append("  PropertyUri: ").Append(PropertyUri).Append("\n");
        sb.Append("  PropertyName: ").Append(PropertyName).Append("\n");
        sb.Append("  DictionaryUri: ").Append(DictionaryUri).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return this.Equals(input as PropertyRelationItemContractV1);
    }

    /// <summary>
    /// Returns true if PropertyRelationItemContractV1 instances are equal
    /// </summary>
    /// <param name="input">Instance of PropertyRelationItemContractV1 to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(PropertyRelationItemContractV1 input)
    {
        if (input == null)
            return false;

        return 
            (
                this.RelationType == input.RelationType ||
                (this.RelationType != null &&
                 this.RelationType.Equals(input.RelationType))
            ) && 
            (
                this.PropertyUri == input.PropertyUri ||
                (this.PropertyUri != null &&
                 this.PropertyUri.Equals(input.PropertyUri))
            ) && 
            (
                this.PropertyName == input.PropertyName ||
                (this.PropertyName != null &&
                 this.PropertyName.Equals(input.PropertyName))
            ) && 
            (
                this.DictionaryUri == input.DictionaryUri ||
                (this.DictionaryUri != null &&
                 this.DictionaryUri.Equals(input.DictionaryUri))
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (this.RelationType != null)
                hashCode = hashCode * 59 + this.RelationType.GetHashCode();
            if (this.PropertyUri != null)
                hashCode = hashCode * 59 + this.PropertyUri.GetHashCode();
            if (this.PropertyName != null)
                hashCode = hashCode * 59 + this.PropertyName.GetHashCode();
            if (this.DictionaryUri != null)
                hashCode = hashCode * 59 + this.DictionaryUri.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}