/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ConsoleDemo.Model;

/// <summary>
/// TextSearchResponseContractV2
/// </summary>
[DataContract]
public partial class TextSearchResponseContractV2 :  IEquatable<TextSearchResponseContractV2>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="TextSearchResponseContractV2" /> class.
    /// </summary>
    /// <param name="totalCount">totalCount.</param>
    /// <param name="offset">offset.</param>
    /// <param name="count">count.</param>
    /// <param name="classes">The list of Classes found.</param>
    /// <param name="dictionaries">The list of Dictionaries with found results.</param>
    /// <param name="properties">List of Properties found.</param>
    public TextSearchResponseContractV2(int? totalCount = default(int?), int? offset = default(int?), int? count = default(int?), List<TextSearchResponseClassContractV2> classes = default(List<TextSearchResponseClassContractV2>), List<TextSearchResponseDictionaryContractV2> dictionaries = default(List<TextSearchResponseDictionaryContractV2>), List<TextSearchResponsePropertyContractV2> properties = default(List<TextSearchResponsePropertyContractV2>))
    {
        this.TotalCount = totalCount;
        this.Offset = offset;
        this.Count = count;
        this.Classes = classes;
        this.Dictionaries = dictionaries;
        this.Properties = properties;
    }
        
    /// <summary>
    /// Gets or Sets TotalCount
    /// </summary>
    [DataMember(Name="totalCount", EmitDefaultValue=false)]
    public int? TotalCount { get; set; }

    /// <summary>
    /// Gets or Sets Offset
    /// </summary>
    [DataMember(Name="offset", EmitDefaultValue=false)]
    public int? Offset { get; set; }

    /// <summary>
    /// Gets or Sets Count
    /// </summary>
    [DataMember(Name="count", EmitDefaultValue=false)]
    public int? Count { get; set; }

    /// <summary>
    /// The list of Classes found
    /// </summary>
    /// <value>The list of Classes found</value>
    [DataMember(Name="classes", EmitDefaultValue=false)]
    public List<TextSearchResponseClassContractV2> Classes { get; set; }

    /// <summary>
    /// The list of Dictionaries with found results
    /// </summary>
    /// <value>The list of Dictionaries with found results</value>
    [DataMember(Name="dictionaries", EmitDefaultValue=false)]
    public List<TextSearchResponseDictionaryContractV2> Dictionaries { get; set; }

    /// <summary>
    /// List of Properties found
    /// </summary>
    /// <value>List of Properties found</value>
    [DataMember(Name="properties", EmitDefaultValue=false)]
    public List<TextSearchResponsePropertyContractV2> Properties { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class TextSearchResponseContractV2 {\n");
        sb.Append("  TotalCount: ").Append(TotalCount).Append("\n");
        sb.Append("  Offset: ").Append(Offset).Append("\n");
        sb.Append("  Count: ").Append(Count).Append("\n");
        sb.Append("  Classes: ").Append(Classes).Append("\n");
        sb.Append("  Dictionaries: ").Append(Dictionaries).Append("\n");
        sb.Append("  Properties: ").Append(Properties).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return this.Equals(input as TextSearchResponseContractV2);
    }

    /// <summary>
    /// Returns true if TextSearchResponseContractV2 instances are equal
    /// </summary>
    /// <param name="input">Instance of TextSearchResponseContractV2 to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(TextSearchResponseContractV2 input)
    {
        if (input == null)
            return false;

        return 
            (
                this.TotalCount == input.TotalCount ||
                (this.TotalCount != null &&
                 this.TotalCount.Equals(input.TotalCount))
            ) && 
            (
                this.Offset == input.Offset ||
                (this.Offset != null &&
                 this.Offset.Equals(input.Offset))
            ) && 
            (
                this.Count == input.Count ||
                (this.Count != null &&
                 this.Count.Equals(input.Count))
            ) && 
            (
                this.Classes == input.Classes ||
                this.Classes != null &&
                input.Classes != null &&
                this.Classes.SequenceEqual(input.Classes)
            ) && 
            (
                this.Dictionaries == input.Dictionaries ||
                this.Dictionaries != null &&
                input.Dictionaries != null &&
                this.Dictionaries.SequenceEqual(input.Dictionaries)
            ) && 
            (
                this.Properties == input.Properties ||
                this.Properties != null &&
                input.Properties != null &&
                this.Properties.SequenceEqual(input.Properties)
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (this.TotalCount != null)
                hashCode = hashCode * 59 + this.TotalCount.GetHashCode();
            if (this.Offset != null)
                hashCode = hashCode * 59 + this.Offset.GetHashCode();
            if (this.Count != null)
                hashCode = hashCode * 59 + this.Count.GetHashCode();
            if (this.Classes != null)
                hashCode = hashCode * 59 + this.Classes.GetHashCode();
            if (this.Dictionaries != null)
                hashCode = hashCode * 59 + this.Dictionaries.GetHashCode();
            if (this.Properties != null)
                hashCode = hashCode * 59 + this.Properties.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}