/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ConsoleDemo.Model;

/// <summary>
/// TextSearchResponseDictionaryContractV2
/// </summary>
[DataContract]
public partial class TextSearchResponseDictionaryContractV2 :  IEquatable<TextSearchResponseDictionaryContractV2>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="TextSearchResponseDictionaryContractV2" /> class.
    /// </summary>
    /// <param name="uri">uri (required).</param>
    /// <param name="organizationName">organizationName (required).</param>
    /// <param name="code">code (required).</param>
    /// <param name="name">name (required).</param>
    /// <param name="version">version (required).</param>
    /// <param name="status">status (required).</param>
    /// <param name="languages">languages (required).</param>
    /// <param name="isLatestVersion">isLatestVersion (required).</param>
    /// <param name="isVerified">isVerified (required).</param>
    public TextSearchResponseDictionaryContractV2(string uri = default(string), string organizationName = default(string), string code = default(string), string name = default(string), string version = default(string), string status = default(string), List<LanguageContractV1> languages = default(List<LanguageContractV1>), bool? isLatestVersion = default(bool?), bool? isVerified = default(bool?))
    {
        // to ensure "uri" is required (not null)
        if (uri == null)
        {
            throw new InvalidDataException("uri is a required property for TextSearchResponseDictionaryContractV2 and cannot be null");
        }
        else
        {
            this.Uri = uri;
        }
        // to ensure "organizationName" is required (not null)
        if (organizationName == null)
        {
            throw new InvalidDataException("organizationName is a required property for TextSearchResponseDictionaryContractV2 and cannot be null");
        }
        else
        {
            this.OrganizationName = organizationName;
        }
        // to ensure "code" is required (not null)
        if (code == null)
        {
            throw new InvalidDataException("code is a required property for TextSearchResponseDictionaryContractV2 and cannot be null");
        }
        else
        {
            this.Code = code;
        }
        // to ensure "name" is required (not null)
        if (name == null)
        {
            throw new InvalidDataException("name is a required property for TextSearchResponseDictionaryContractV2 and cannot be null");
        }
        else
        {
            this.Name = name;
        }
        // to ensure "version" is required (not null)
        if (version == null)
        {
            throw new InvalidDataException("version is a required property for TextSearchResponseDictionaryContractV2 and cannot be null");
        }
        else
        {
            this.Version = version;
        }
        // to ensure "status" is required (not null)
        if (status == null)
        {
            throw new InvalidDataException("status is a required property for TextSearchResponseDictionaryContractV2 and cannot be null");
        }
        else
        {
            this.Status = status;
        }
        // to ensure "languages" is required (not null)
        if (languages == null)
        {
            throw new InvalidDataException("languages is a required property for TextSearchResponseDictionaryContractV2 and cannot be null");
        }
        else
        {
            this.Languages = languages;
        }
        // to ensure "isLatestVersion" is required (not null)
        if (isLatestVersion == null)
        {
            throw new InvalidDataException("isLatestVersion is a required property for TextSearchResponseDictionaryContractV2 and cannot be null");
        }
        else
        {
            this.IsLatestVersion = isLatestVersion;
        }
        // to ensure "isVerified" is required (not null)
        if (isVerified == null)
        {
            throw new InvalidDataException("isVerified is a required property for TextSearchResponseDictionaryContractV2 and cannot be null");
        }
        else
        {
            this.IsVerified = isVerified;
        }
    }
        
    /// <summary>
    /// Gets or Sets Uri
    /// </summary>
    [DataMember(Name="uri", EmitDefaultValue=false)]
    public string Uri { get; set; }

    /// <summary>
    /// Gets or Sets OrganizationName
    /// </summary>
    [DataMember(Name="organizationName", EmitDefaultValue=false)]
    public string OrganizationName { get; set; }

    /// <summary>
    /// Gets or Sets Code
    /// </summary>
    [DataMember(Name="code", EmitDefaultValue=false)]
    public string Code { get; set; }

    /// <summary>
    /// Gets or Sets Name
    /// </summary>
    [DataMember(Name="name", EmitDefaultValue=false)]
    public string Name { get; set; }

    /// <summary>
    /// Gets or Sets Version
    /// </summary>
    [DataMember(Name="version", EmitDefaultValue=false)]
    public string Version { get; set; }

    /// <summary>
    /// Gets or Sets Status
    /// </summary>
    [DataMember(Name="status", EmitDefaultValue=false)]
    public string Status { get; set; }

    /// <summary>
    /// Gets or Sets Languages
    /// </summary>
    [DataMember(Name="languages", EmitDefaultValue=false)]
    public List<LanguageContractV1> Languages { get; set; }

    /// <summary>
    /// Gets or Sets IsLatestVersion
    /// </summary>
    [DataMember(Name="isLatestVersion", EmitDefaultValue=false)]
    public bool? IsLatestVersion { get; set; }

    /// <summary>
    /// Gets or Sets IsVerified
    /// </summary>
    [DataMember(Name="isVerified", EmitDefaultValue=false)]
    public bool? IsVerified { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class TextSearchResponseDictionaryContractV2 {\n");
        sb.Append("  Uri: ").Append(Uri).Append("\n");
        sb.Append("  OrganizationName: ").Append(OrganizationName).Append("\n");
        sb.Append("  Code: ").Append(Code).Append("\n");
        sb.Append("  Name: ").Append(Name).Append("\n");
        sb.Append("  Version: ").Append(Version).Append("\n");
        sb.Append("  Status: ").Append(Status).Append("\n");
        sb.Append("  Languages: ").Append(Languages).Append("\n");
        sb.Append("  IsLatestVersion: ").Append(IsLatestVersion).Append("\n");
        sb.Append("  IsVerified: ").Append(IsVerified).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }
  
    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return this.Equals(input as TextSearchResponseDictionaryContractV2);
    }

    /// <summary>
    /// Returns true if TextSearchResponseDictionaryContractV2 instances are equal
    /// </summary>
    /// <param name="input">Instance of TextSearchResponseDictionaryContractV2 to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(TextSearchResponseDictionaryContractV2 input)
    {
        if (input == null)
            return false;

        return 
            (
                this.Uri == input.Uri ||
                (this.Uri != null &&
                 this.Uri.Equals(input.Uri))
            ) && 
            (
                this.OrganizationName == input.OrganizationName ||
                (this.OrganizationName != null &&
                 this.OrganizationName.Equals(input.OrganizationName))
            ) && 
            (
                this.Code == input.Code ||
                (this.Code != null &&
                 this.Code.Equals(input.Code))
            ) && 
            (
                this.Name == input.Name ||
                (this.Name != null &&
                 this.Name.Equals(input.Name))
            ) && 
            (
                this.Version == input.Version ||
                (this.Version != null &&
                 this.Version.Equals(input.Version))
            ) && 
            (
                this.Status == input.Status ||
                (this.Status != null &&
                 this.Status.Equals(input.Status))
            ) && 
            (
                this.Languages == input.Languages ||
                this.Languages != null &&
                input.Languages != null &&
                this.Languages.SequenceEqual(input.Languages)
            ) && 
            (
                this.IsLatestVersion == input.IsLatestVersion ||
                (this.IsLatestVersion != null &&
                 this.IsLatestVersion.Equals(input.IsLatestVersion))
            ) && 
            (
                this.IsVerified == input.IsVerified ||
                (this.IsVerified != null &&
                 this.IsVerified.Equals(input.IsVerified))
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (this.Uri != null)
                hashCode = hashCode * 59 + this.Uri.GetHashCode();
            if (this.OrganizationName != null)
                hashCode = hashCode * 59 + this.OrganizationName.GetHashCode();
            if (this.Code != null)
                hashCode = hashCode * 59 + this.Code.GetHashCode();
            if (this.Name != null)
                hashCode = hashCode * 59 + this.Name.GetHashCode();
            if (this.Version != null)
                hashCode = hashCode * 59 + this.Version.GetHashCode();
            if (this.Status != null)
                hashCode = hashCode * 59 + this.Status.GetHashCode();
            if (this.Languages != null)
                hashCode = hashCode * 59 + this.Languages.GetHashCode();
            if (this.IsLatestVersion != null)
                hashCode = hashCode * 59 + this.IsLatestVersion.GetHashCode();
            if (this.IsVerified != null)
                hashCode = hashCode * 59 + this.IsVerified.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}