/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ConsoleDemo.Model;

/// <summary>
/// TextSearchResponsePropertyContractV1
/// </summary>
[DataContract]
public partial class TextSearchResponsePropertyContractV1 :  IEquatable<TextSearchResponsePropertyContractV1>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="TextSearchResponsePropertyContractV1" /> class.
    /// </summary>
    /// <param name="dictionaryUri">dictionaryUri.</param>
    /// <param name="dictionaryName">dictionaryName.</param>
    /// <param name="uri">uri.</param>
    /// <param name="name">name.</param>
    /// <param name="description">description.</param>
    public TextSearchResponsePropertyContractV1(string dictionaryUri = default(string), string dictionaryName = default(string), string uri = default(string), string name = default(string), string description = default(string))
    {
        this.DictionaryUri = dictionaryUri;
        this.DictionaryName = dictionaryName;
        this.Uri = uri;
        this.Name = name;
        this.Description = description;
    }
        
    /// <summary>
    /// Gets or Sets DictionaryUri
    /// </summary>
    [DataMember(Name="dictionaryUri", EmitDefaultValue=false)]
    public string DictionaryUri { get; set; }

    /// <summary>
    /// Gets or Sets DictionaryName
    /// </summary>
    [DataMember(Name="dictionaryName", EmitDefaultValue=false)]
    public string DictionaryName { get; set; }

    /// <summary>
    /// Gets or Sets Uri
    /// </summary>
    [DataMember(Name="uri", EmitDefaultValue=false)]
    public string Uri { get; set; }

    /// <summary>
    /// Gets or Sets Name
    /// </summary>
    [DataMember(Name="name", EmitDefaultValue=false)]
    public string Name { get; set; }

    /// <summary>
    /// Gets or Sets Description
    /// </summary>
    [DataMember(Name="description", EmitDefaultValue=false)]
    public string Description { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class TextSearchResponsePropertyContractV1 {\n");
        sb.Append("  DictionaryUri: ").Append(DictionaryUri).Append("\n");
        sb.Append("  DictionaryName: ").Append(DictionaryName).Append("\n");
        sb.Append("  Uri: ").Append(Uri).Append("\n");
        sb.Append("  Name: ").Append(Name).Append("\n");
        sb.Append("  Description: ").Append(Description).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }
  
    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return this.Equals(input as TextSearchResponsePropertyContractV1);
    }

    /// <summary>
    /// Returns true if TextSearchResponsePropertyContractV1 instances are equal
    /// </summary>
    /// <param name="input">Instance of TextSearchResponsePropertyContractV1 to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(TextSearchResponsePropertyContractV1 input)
    {
        if (input == null)
            return false;

        return 
            (
                this.DictionaryUri == input.DictionaryUri ||
                (this.DictionaryUri != null &&
                 this.DictionaryUri.Equals(input.DictionaryUri))
            ) && 
            (
                this.DictionaryName == input.DictionaryName ||
                (this.DictionaryName != null &&
                 this.DictionaryName.Equals(input.DictionaryName))
            ) && 
            (
                this.Uri == input.Uri ||
                (this.Uri != null &&
                 this.Uri.Equals(input.Uri))
            ) && 
            (
                this.Name == input.Name ||
                (this.Name != null &&
                 this.Name.Equals(input.Name))
            ) && 
            (
                this.Description == input.Description ||
                (this.Description != null &&
                 this.Description.Equals(input.Description))
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (this.DictionaryUri != null)
                hashCode = hashCode * 59 + this.DictionaryUri.GetHashCode();
            if (this.DictionaryName != null)
                hashCode = hashCode * 59 + this.DictionaryName.GetHashCode();
            if (this.Uri != null)
                hashCode = hashCode * 59 + this.Uri.GetHashCode();
            if (this.Name != null)
                hashCode = hashCode * 59 + this.Name.GetHashCode();
            if (this.Description != null)
                hashCode = hashCode * 59 + this.Description.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}