/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ConsoleDemo.Model;

/// <summary>
/// UploadImportFileResultV2
/// </summary>
[DataContract]
public partial class UploadImportFileResultV2 :  IEquatable<UploadImportFileResultV2>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="UploadImportFileResultV2" /> class.
    /// </summary>
    /// <param name="isValidatedAsync">Indicates if the file will be validated in the background.  Large files (&gt;&#x3D; 15 MB) will be validated in the background. You receive the results by e-mail..</param>
    /// <param name="isOk">Indicates if the file will be imported.  Warnings are allowed, import will continue but may lead to undesired values in the database.  Only applicable for small files (smaller than 15 MB)..</param>
    /// <param name="errors">The list of errors found.  It may happen that if you fix one error new errors will be discovered..</param>
    /// <param name="warnings">List of warnings.  It is best to have no warnings at all to avoid inconsistent or incorrect values in the database.</param>
    /// <param name="informationalMessages">Informational messages.</param>
    public UploadImportFileResultV2(bool? isValidatedAsync = default(bool?), bool? isOk = default(bool?), List<UploadImportFileResultItemV2> errors = default(List<UploadImportFileResultItemV2>), List<UploadImportFileResultItemV2> warnings = default(List<UploadImportFileResultItemV2>), List<UploadImportFileResultItemV2> informationalMessages = default(List<UploadImportFileResultItemV2>))
    {
        this.IsValidatedAsync = isValidatedAsync;
        this.IsOk = isOk;
        this.Errors = errors;
        this.Warnings = warnings;
        this.InformationalMessages = informationalMessages;
    }
        
    /// <summary>
    /// Indicates if the file will be validated in the background.  Large files (&gt;&#x3D; 15 MB) will be validated in the background. You receive the results by e-mail.
    /// </summary>
    /// <value>Indicates if the file will be validated in the background.  Large files (&gt;&#x3D; 15 MB) will be validated in the background. You receive the results by e-mail.</value>
    [DataMember(Name="isValidatedAsync", EmitDefaultValue=false)]
    public bool? IsValidatedAsync { get; set; }

    /// <summary>
    /// Indicates if the file will be imported.  Warnings are allowed, import will continue but may lead to undesired values in the database.  Only applicable for small files (smaller than 15 MB).
    /// </summary>
    /// <value>Indicates if the file will be imported.  Warnings are allowed, import will continue but may lead to undesired values in the database.  Only applicable for small files (smaller than 15 MB).</value>
    [DataMember(Name="isOk", EmitDefaultValue=false)]
    public bool? IsOk { get; set; }

    /// <summary>
    /// The list of errors found.  It may happen that if you fix one error new errors will be discovered.
    /// </summary>
    /// <value>The list of errors found.  It may happen that if you fix one error new errors will be discovered.</value>
    [DataMember(Name="errors", EmitDefaultValue=false)]
    public List<UploadImportFileResultItemV2> Errors { get; set; }

    /// <summary>
    /// List of warnings.  It is best to have no warnings at all to avoid inconsistent or incorrect values in the database
    /// </summary>
    /// <value>List of warnings.  It is best to have no warnings at all to avoid inconsistent or incorrect values in the database</value>
    [DataMember(Name="warnings", EmitDefaultValue=false)]
    public List<UploadImportFileResultItemV2> Warnings { get; set; }

    /// <summary>
    /// Informational messages
    /// </summary>
    /// <value>Informational messages</value>
    [DataMember(Name="informationalMessages", EmitDefaultValue=false)]
    public List<UploadImportFileResultItemV2> InformationalMessages { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class UploadImportFileResultV2 {\n");
        sb.Append("  IsValidatedAsync: ").Append(IsValidatedAsync).Append("\n");
        sb.Append("  IsOk: ").Append(IsOk).Append("\n");
        sb.Append("  Errors: ").Append(Errors).Append("\n");
        sb.Append("  Warnings: ").Append(Warnings).Append("\n");
        sb.Append("  InformationalMessages: ").Append(InformationalMessages).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return this.Equals(input as UploadImportFileResultV2);
    }

    /// <summary>
    /// Returns true if UploadImportFileResultV2 instances are equal
    /// </summary>
    /// <param name="input">Instance of UploadImportFileResultV2 to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(UploadImportFileResultV2 input)
    {
        if (input == null)
            return false;

        return 
            (
                this.IsValidatedAsync == input.IsValidatedAsync ||
                (this.IsValidatedAsync != null &&
                 this.IsValidatedAsync.Equals(input.IsValidatedAsync))
            ) && 
            (
                this.IsOk == input.IsOk ||
                (this.IsOk != null &&
                 this.IsOk.Equals(input.IsOk))
            ) && 
            (
                this.Errors == input.Errors ||
                this.Errors != null &&
                input.Errors != null &&
                this.Errors.SequenceEqual(input.Errors)
            ) && 
            (
                this.Warnings == input.Warnings ||
                this.Warnings != null &&
                input.Warnings != null &&
                this.Warnings.SequenceEqual(input.Warnings)
            ) && 
            (
                this.InformationalMessages == input.InformationalMessages ||
                this.InformationalMessages != null &&
                input.InformationalMessages != null &&
                this.InformationalMessages.SequenceEqual(input.InformationalMessages)
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (this.IsValidatedAsync != null)
                hashCode = hashCode * 59 + this.IsValidatedAsync.GetHashCode();
            if (this.IsOk != null)
                hashCode = hashCode * 59 + this.IsOk.GetHashCode();
            if (this.Errors != null)
                hashCode = hashCode * 59 + this.Errors.GetHashCode();
            if (this.Warnings != null)
                hashCode = hashCode * 59 + this.Warnings.GetHashCode();
            if (this.InformationalMessages != null)
                hashCode = hashCode * 59 + this.InformationalMessages.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}