/* 
 * Dictionaries API
 *
 * <p>API to access the buildingSMART Data Dictionary.</p><p>For manually uploading import files, please go to <a href=\"https://manage.bsdd.buildingsmart.org\">bSDD Management portal</a>. Version history can be found at <a href=\"https://github.com/buildingSMART/bSDD/blob/master/API%20version%20history.md\">Version history</a>.</p><p>Keep an eye on (planned) updates: <a href=\"https://forums.buildingsmart.org/t/bsdd-tech-updates/4889\">bSDD tech updates</a></p><h3>For client developers</h3><p>If you're creating a desktop client that only calls the not secured APIs, you're ready to go.<br/>If you don't use the secured APIs but want to call the other APIs from your website or SPA, then we need the URL of your website to allow CORS.</p><p>If you are going to build a client that is going to use secured APIs, you must request a Client ID. You can do so by sending us an email and give:</p><ul><li>the name of the client application</li><li>type of application:<ul><li>Web application</li><li>Single-page application</li><li>iOS / macOS, Object-C, Swift, Xamarin</li><li>Adroid - Java, Kotlin, Xamarin</li><li>Mobile/desktop</li></ul> <li>which development language are you using? (sometimes the redirectUri to be configured depends on the used library)</li><li>if it is a website or SPA, specify the return url (the login page will redirect to this url after user has logged in)</li></ul>
 *
 * OpenAPI spec version: v1
 * Contact: bsdd_support@buildingsmart.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace ConsoleDemo.Model;

/// <summary>
/// UploadImportFileV2Body
/// </summary>
[DataContract]
public partial class UploadImportFileV2Body :  IEquatable<UploadImportFileV2Body>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="UploadImportFileV2Body" /> class.
    /// </summary>
    /// <param name="organizationCode">Code of the organization owning the dictionary.  If you do not know the code, contact us (see e-mail address on top of this page) (required).</param>
    /// <param name="formFile">The bsdd import file in json format (required).</param>
    /// <param name="validateOnly">Set to true if you only want to validate the file. Even when there are no validation errors the file wil not be imported.  The validation result will not be send via e-mail..</param>
    /// <param name="isTest">Set to true if you are just testing your file. Data will be stored in the database, you can retrieve it via the API, but you can&#x27;t set status to Active.  Dictionary will be deleted after 60 days of last upload..</param>
    public UploadImportFileV2Body(string organizationCode = default(string), byte[] formFile = default(byte[]), bool? validateOnly = default(bool?), bool? isTest = default(bool?))
    {
        // to ensure "organizationCode" is required (not null)
        if (string.IsNullOrWhiteSpace(organizationCode))
        {
            throw new InvalidDataException("organizationCode is a required property for UploadImportFileV2Body and cannot be null");
        }
        else
        {
            this.OrganizationCode = organizationCode;
        }
        // to ensure "formFile" is required (not null)
        if (formFile == null)
        {
            throw new InvalidDataException("formFile is a required property for UploadImportFileV2Body and cannot be null");
        }
        else
        {
            this.FormFile = formFile;
        }
        this.ValidateOnly = validateOnly;
        this.IsTest = isTest;
    }
        
    /// <summary>
    /// Code of the organization owning the dictionary.  If you do not know the code, contact us (see e-mail address on top of this page)
    /// </summary>
    /// <value>Code of the organization owning the dictionary.  If you do not know the code, contact us (see e-mail address on top of this page)</value>
    [DataMember(Name="OrganizationCode", EmitDefaultValue=false)]
    public string OrganizationCode { get; set; }

    /// <summary>
    /// The bsdd import file in json format
    /// </summary>
    /// <value>The bsdd import file in json format</value>
    [DataMember(Name="FormFile", EmitDefaultValue=false)]
    public byte[] FormFile { get; set; }

    /// <summary>
    /// Set to true if you only want to validate the file. Even when there are no validation errors the file wil not be imported.  The validation result will not be send via e-mail.
    /// </summary>
    /// <value>Set to true if you only want to validate the file. Even when there are no validation errors the file wil not be imported.  The validation result will not be send via e-mail.</value>
    [DataMember(Name="ValidateOnly", EmitDefaultValue=false)]
    public bool? ValidateOnly { get; set; }

    /// <summary>
    /// Set to true if you are just testing your file. Data will be stored in the database, you can retrieve it via the API, but you can&#x27;t set status to Active.  Dictionary will be deleted after 60 days of last upload.
    /// </summary>
    /// <value>Set to true if you are just testing your file. Data will be stored in the database, you can retrieve it via the API, but you can&#x27;t set status to Active.  Dictionary will be deleted after 60 days of last upload.</value>
    [DataMember(Name="IsTest", EmitDefaultValue=false)]
    public bool? IsTest { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class UploadImportFileV2Body {\n");
        sb.Append("  OrganizationCode: ").Append(OrganizationCode).Append("\n");
        sb.Append("  FormFile: ").Append(FormFile).Append("\n");
        sb.Append("  ValidateOnly: ").Append(ValidateOnly).Append("\n");
        sb.Append("  IsTest: ").Append(IsTest).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return this.Equals(input as UploadImportFileV2Body);
    }

    /// <summary>
    /// Returns true if UploadImportFileV2Body instances are equal
    /// </summary>
    /// <param name="input">Instance of UploadImportFileV2Body to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(UploadImportFileV2Body input)
    {
        if (input == null)
            return false;

        return 
            (
                this.OrganizationCode == input.OrganizationCode ||
                (this.OrganizationCode != null &&
                 this.OrganizationCode.Equals(input.OrganizationCode))
            ) && 
            (
                this.FormFile == input.FormFile ||
                (this.FormFile != null &&
                 this.FormFile.Equals(input.FormFile))
            ) && 
            (
                this.ValidateOnly == input.ValidateOnly ||
                (this.ValidateOnly != null &&
                 this.ValidateOnly.Equals(input.ValidateOnly))
            ) && 
            (
                this.IsTest == input.IsTest ||
                (this.IsTest != null &&
                 this.IsTest.Equals(input.IsTest))
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            int hashCode = 41;
            if (this.OrganizationCode != null)
                hashCode = hashCode * 59 + this.OrganizationCode.GetHashCode();
            if (this.FormFile != null)
                hashCode = hashCode * 59 + this.FormFile.GetHashCode();
            if (this.ValidateOnly != null)
                hashCode = hashCode * 59 + this.ValidateOnly.GetHashCode();
            if (this.IsTest != null)
                hashCode = hashCode * 59 + this.IsTest.GetHashCode();
            return hashCode;
        }
    }

    /// <summary>
    /// To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }
}